# https://argo-cd.readthedocs.io/en/stable/getting_started
# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation
---
- name: Install Argo CD GitOps tool
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  gather_facts: false
  vars_files:
    - vars/kubernetes.yml
    - vars/valkey.yml
    - vars/gitlab.yml
    - vars/monitoring.yml
    - vars/argocd.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ argocd_namespace }}"
    create_ns: false
    release: "{{ argocd_release_name }}"
  pre_tasks:
    - name: Get CA certificates from PKI
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/pki/cacerts.yml
      when: ca_certificates is not defined

    - name: Get GitLab shell known hosts
      vars:
        ssh_host: "{{ gitlab_fqdns['gitlab'] }}"
        ssh_port: "{{ gitlab_shell_port }}"
      ansible.builtin.include_tasks: tasks/hosts/knownhosts.yml
      # sets known_hosts fact

    - name: Set gitlab_known_hosts fact
      vars:
        # since we're using non-standard SSH port, first field is [host]:port
        svc_hosts: "{{ known_hosts | map('regex_replace', '^[^:]+', '['~ gitlab_shell_host ~']') }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        gitlab_known_hosts: "{{ (known_hosts + svc_hosts) | join('\n') }}"
  tasks:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/tls#tls-certificates-used-by-argocd-server
    - name: Create Argo CD ingress secret
      vars:
        secret_name: "{{ argocd_secrets['server'] }}"
        create_ns: true
        cert_name: argocd-server-ingress
        sans:
          - argocd
          - "{{ argocd_fqdn }}"
          - "*.{{ argocd_namespace }}.svc.{{ cluster_domain }}"
          - "*.{{ argocd_namespace }}.svc"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Create Valkey password secret
      vars:
        secret_name: "{{ argocd_secrets['valkey'] }}"
        secret_data:
          redis-password: "{{ valkey_pass }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/generic.yml

    - name: Install Argo CD Helm chart
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        chart_repo_url: https://argoproj.github.io/argo-helm
        chart_ref: argo-cd
        chart_version: "{{ argocd_chart_version }}"
        release_name: "{{ argocd_release_name }}"
        release_namespace: "{{ argocd_namespace }}"
        release_values: "{{ argocd_chart_values }}"
        history_max: "{{ helm_max_history }}"
        atomic: true
        wait: true
      timeout: 300

    - name: >-
        {{ 'Enable' if enabled else 'Disable' }}
        Istio service mesh
      vars:
        enabled: "{{ argocd_use_mesh }}"
        apps_ns: "{{ argocd_namespace }}"
        services:
          - argocd-server
          - argocd-applicationset-controller
          - argocd-commit-server
          - argocd-repo-server
        resources: |
          {% set res = [] %}
          {% for svc in services %}
          {%  set _ = res.append({
                'kind':'Service',
                'name': svc
              }) %}
          {% endfor %}
          {{ res }}
      ansible.builtin.include_tasks: tasks/istio/mesh.yml
  any_errors_fatal: true
