# this playbook is only run within an AWX workflow
# as the initial job template to create "temp.yml"
# under /var/lib/awx/tmp/ containing playbooks to
# run based on the user's Select Playbooks survey
---
- name: Create temporary runlist
  hosts: localhost
  gather_facts: false
  vars:
    temp_dir: /var/lib/awx/tmp/homelab-k8s
  pre_tasks:
    # PLAYBOOKS is a survey variable
    - name: Assert PLAYBOOKS defined
      ansible.builtin.assert:
        that:
          - PLAYBOOKS is defined
          - PLAYBOOKS is iterable
          # it's OK if it's empty

    - name: Make sure temp dir exists
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
      ansible.builtin.file:
        path: "{{ temp_dir }}"
        state: directory
        mode: "0755"
  tasks:
    - name: Create temporary runlist
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      # noqa risky-shell-pipe
      ansible.builtin.shell: |
        cd /runner/project

        args=({{ '' if 'ALL' in PLAYBOOKS else PLAYBOOKS | join(' ') }})
        ./runlist.sh "${args[@]}" || exit 1

        # change playbook paths to /runner/project/* (Git project root)
        # because awx.execute.yml loads temp.yml from /var/lib/awx/tmp/
        perl -pX -i -e 's|(?<=import_playbook:\s)|/runner/project/|g' temp.yml
        mv -f temp.yml {{ temp_dir }}
      changed_when: true
  post_tasks:
    - name: Output temporary runlist
      vars:
        # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/file_lookup.html
        runlist: "{{ lookup('ansible.builtin.file', temp_dir ~ '/temp.yml') | from_yaml }}"
        # https://docs.ansible.com/projects/ansible/latest/collections/community/general/json_query_filter.html
        playbooks: "{{ runlist | community.general.json_query('[].\"ansible.builtin.import_playbook\"') }}"
      ansible.builtin.debug:
        var: playbooks
