# https://external-secrets.io/
# https://external-secrets.io/latest/provider/hashicorp-vault
# https://external-secrets.io/latest/api/clustersecretstore
---
- name: Install External Secrets Operator
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/vault.yml
    - vars/externalsecrets.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
  pre_tasks:
    - name: Does ClusterSecretStore CRD exist?
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        # name must be in plural form!
        name: clustersecretstores.external-secrets.io
      register: crd_info
  tasks:
    # https://external-secrets.io/latest/introduction/getting-started
    - name: Install External Secrets Helm chart
      vars:
        secretstore_ref: >-
          external-secrets.io/v1 ClusterSecretStore {{ eso_secretstore_cr.metadata.name }}

        # === Inputs ===
        repo_name: eso
        repo_url: https://charts.external-secrets.io
        chart_ref: external-secrets
        chart_ver: "{{ eso_chart_version }}"
        release: "{{ eso_release_name }}"
        release_ns: "{{ eso_namespace }}"
        values: "{{ eso_chart_values }}"

        extras: # adopt extra resources into Helm release
          - "{{ secretstore_ref if crd_info.resources is truthy else '' }}"
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml

    # cannot include CRs as extraObjects of Helm
    # chart because CRDs must be installed first
    - name: Create ClusterSecretStore for Vault
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        definition: "{{ eso_secretstore_cr }}"
        state: present
        apply: true
      when: crd_info.resources is falsy
