# https://external-secrets.io/
# https://external-secrets.io/latest/provider/hashicorp-vault
# https://external-secrets.io/latest/api/clustersecretstore
---
- name: Install External Secrets Operator
  hosts: "{{ rke_control_plane_host }}"
  gather_facts: false
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/vault.yml
    - vars/externalsecrets.yml
  tasks:
    # https://external-secrets.io/latest/introduction/getting-started
    - name: Install External Secrets Helm chart
      vars:
        # required kubernetes>=24.2 package only in user virtualenv
        ansible_python_interpreter: "{{ venv_python_interpreter }}"
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
      kubernetes.core.helm:
        kubeconfig: "{{ rke_kubeconfig }}"
        chart_repo_url: https://charts.external-secrets.io
        chart_ref: external-secrets
        chart_version: "{{ eso_chart_version }}"
        release_name: "{{ eso_release_name }}"
        release_namespace: "{{ eso_namespace }}"
        create_namespace: true
        release_values: "{{ eso_chart_values }}"
        history_max: "{{ helm_max_history }}"
        atomic: true
        wait: true
  any_errors_fatal: true
