---
- name: Set up admin user's home directory
  hosts: k8s_hosts
  vars_files:
    - vars/files.yml
    - vars/kubernetes.yml
    - vars/rancher.yml
  tasks:
    - name: Allow sudo commands without password
      become: true
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
      ansible.builtin.template:
        src: "{{ template_dir }}/linux/nopasswd.j2"
        dest: /etc/sudoers.d/nopasswd
        mode: "0440"

    - name: Suppress Apt script warning message
      become: true
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/90disable-warning
        content: |
          Apt::Cmd::Disable-Script-Warning true;
        mode: "0644"

    - name: Copy dot files into home directory
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/{{ item }}"
        dest: "{{ ansible_user_dir }}/{{ item }}"
        mode: "0644"
        directory_mode: "0755"
      loop: "{{ copy_files }}"
      notify: Touch copied files

    - name: Upload Rancher API Bash functions
      ansible.builtin.template:
        src: "{{ template_dir }}/rancher/api.sh.j2"
        dest: "{{ ansible_user_dir }}/.rancher_api"
        mode: "0644"
      when: inventory_hostname == k3s_control_plane_host
      notify: Touch copied files
  handlers:
    - name: Touch copied files
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        # restart Bash and load .bash_aliases
        # in order to use my custom functions
        exec /bin/bash <<'EOT'
        ADMIN_PASS=none
        . .bash_aliases

        # zeros out file time MM:ss
        _touch -t 00 . .sudo_as_* .rancher_*
        # now do the same again but recursively
        touchall -t 00 {{ copy_files | map('quote') | join(' ') }}
        EOT
      changed_when: true
