# https://docs.fluentbit.io/manual
# https://chronosphere.io/fluent-bit-academy
# https://github.com/fluent/fluent-operator
---
- name: Install Fluent Bit on RKE cluster
  tags: fluentbit
  hosts: "{{ rke_control_plane_host }}"
  vars_files: &vars_files
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/opensearch.yml
    - vars/logging.yml
    - vars/kibana.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ logging_namespace }}"
    create_ns: false
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/monitoring/stackready.yml
      when: monitoring_stack_ready is not defined
  tasks:
    - name: Create Fluent credentials secret
      vars:
        secret_name: "{{ logging_secrets['credentials'] }}"
        secret_data:
          opensearch-username: "{{ fluent_os_user }}"
          opensearch-password: "{{ fluent_os_pass }}"
        create_ns: true
      ansible.builtin.include_tasks: tasks/k8s/secrets/generic.yml

    # https://docs.fluentbit.io/manual/administration/transport-security
    - name: Create Fluent plugin secret
      vars:
        secret_name: "{{ logging_secrets['plugin'] }}"
        cert_name: fluent-plugin
        algorithm: RSA
        days: 365
        sans:
          - "{{ fluent_os_user }}"
          - "{{ fluent_os_user }}@{{ homelab_domain }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Install Fluent Operator Helm chart
      vars:
        repo_name: fluent
        repo_url: https://fluent.github.io/helm-charts
        chart_ref: fluent-operator
        chart_ver: "{{ fluent_operator_chart_version }}"
        release: "{{ fluent_operator_release_name }}"
        release_ns: "{{ logging_namespace }}"
        values: "{{ fluent_operator_chart_values }}"

        patches:
          merge_patches:
            # https://github.com/fluent/helm-charts/issues/605
            # https://github.com/fluent/helm-charts/pull/607
            - |
              {% if prometheus_crds_installed %}
              apiVersion: monitoring.coreos.com/v1
              kind: ServiceMonitor
              metadata:
                name: fluent-bit
                namespace: {{ logging_namespace }}
                labels:
                  release: {{ monitoring_release_name }}
              {% endif %}

          json_patches:
            # https://github.com/fluent/helm-charts/tree/main/charts/fluent-operator/templates/fluentbit-clusterfilter-kubernetes.yaml
            - target:
                group: fluentbit.fluent.io
                version: v1alpha2
                kind: ClusterFilter
                name: kubernetes
              patch:
                - op: replace
                  path: /spec/filters/2/modify/rules
                  # https://docs.ansible.com/ansible/latest/collections/community/general/dict_kv_filter.html
                  value: "{{ remove_log_fields | map('community.general.dict_kv', 'remove') }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ logging_secrets['plugin'] }}
          - v1 Secret {{ logging_secrets['credentials'] }}
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml

    - name: Configure Fluent logs ISM policy
      vars:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_lookup.html
        policy: "{{ lookup('ansible.builtin.template',
          template_dir ~ '/logging/ismpolicy.yaml.j2') | from_yaml }}"
      ansible.builtin.include_tasks: tasks/opensearch/ismpolicy.yml

- name: Configure logging dashboards
  tags: dashboards
  hosts: "{{ rke_control_plane_host }}"
  vars_files: *vars_files
  vars:
    log_search: "{{ saved_log_search }}"
  tasks:
    - name: Create index pattern for logs
      vars:
        pattern: "{{ log_search.index_pattern }}"
        time_field: "{{ log_search.time_field }}"
      ansible.builtin.include_tasks: tasks/kibana/indexpat.yml
      # sets index_pattern_id fact

    - name: Create saved search for logs
      vars:
        title: "{{ log_search.title }}"
        description: "{{ log_search.description }}"
        fields: "{{ log_search.selected_fields }}"
        patterns: "{{ [log_search.index_pattern] }}"
      ansible.builtin.include_tasks: tasks/kibana/search.yml
      # sets saved_search_id fact

    - name: Set Dashboards landing page
      vars:
        username: admin
        password: "{{ opensearch_admin_pass }}"
        settings:
          defaultRoute: "/app/data-explorer/discover/#/view/{{ saved_search_id }}"
      ansible.builtin.include_tasks: tasks/kibana/settings.yml

    - name: Import Grafana dashboards
      vars:
        dashboards: "{{ logging_grafana_dashboards }}"
      ansible.builtin.include_tasks: tasks/grafana/dashboards.yml
      when: grafana_api_server_online | default(true)
