---
- name: Include package installs playbook
  ansible.builtin.import_playbook: packages.yml
  tags: packages

- name: Include system settings playbook
  ansible.builtin.import_playbook: basics.yml
  tags: basics

- name: Include home directory setup playbook
  ansible.builtin.import_playbook: files.yml
  tags: files

- name: Include Rancher K3s cluster playbook
  ansible.builtin.import_playbook: rancher.yml
  tags: rancher

# NOTE: if initial cluster installation fails, restart
# from rancher.yml playbook to obtain the registration
# manifest URL, or else cluster.yml playbook will just
# spin waiting for Rancher cluster agents to be ready
- name: Include Rancher RKE cluster playbook
  ansible.builtin.import_playbook: cluster.yml
  tags: cluster

- name: Include cert-manager and PKI playbook
  ansible.builtin.import_playbook: certmanager.yml
  tags: certmanager

- name: Include storage provisioners playbook
  ansible.builtin.import_playbook: storage.yml
  tags: storage

# MinIO depends on NFS storage provisioner
- name: Include MinIO object storage playbook
  ansible.builtin.import_playbook: minio.yml
  tags: minio

# Velero depends on MinIO and Longhorn
- name: Include Velero backup/restore playbook
  ansible.builtin.import_playbook: velero.yml
  tags: velero

# Harbor depends on NFS storage provisioner
- name: Include Harbor OCI registry playbook
  ansible.builtin.import_playbook: harbor.yml
  tags: harbor

- name: Include resource manifests playbook
  ansible.builtin.import_playbook: manifests.yml
  tags: manifests

# Intel Device Plugins depends on cert-manager
- name: Include Node Feature Discovery playbook
  ansible.builtin.import_playbook: nodefeatures.yml
  tags: nodefeatures

- name: Include OpenSearch cluster playbook
  ansible.builtin.import_playbook: opensearch.yml
  tags: opensearch

# Fluent Bit depends on OpenSearch
- name: Include Fluent Bit logging playbook
  ansible.builtin.import_playbook: logging.yml
  tags: logging

- name: Include PostgreSQL database playbook
  ansible.builtin.import_playbook: postgresql.yml
  tags: postgresql

# Keycloak depends on PostgreSQL
- name: Include Keycloak IAM & OIDC playbook
  ansible.builtin.import_playbook: keycloak.yml
  tags: keycloak

- name: Include Valkey cache cluster playbook
  ansible.builtin.import_playbook: valkey.yml
  tags: valkey

# Prometheus depends on Keycloak and Valkey
- name: Include Prometheus monitoring playbook
  ansible.builtin.import_playbook: monitoring.yml
  tags: monitoring

# Thanos depends on Prometheus and Valkey
- name: Include Thanos components playbook
  ansible.builtin.import_playbook: thanos.yml
  tags: thanos

# Kiali depends on Prometheus and Keycloak
- name: Include Istio service mesh playbook
  ansible.builtin.import_playbook: istio.yml
  tags: istio

# Argo CD depends on Valkey
- name: Include Argo CD GitOps tool playbook
  ansible.builtin.import_playbook: argocd.yml
  tags: argocd

- name: Include K8s Metacontroller playbook
  ansible.builtin.import_playbook: metacontroller.yml
  tags: metacontroller

- name: Include Ollama LLM server playbook
  ansible.builtin.import_playbook: ollama.yml
  tags: ollama

- name: Include virtual clusters playbook
  ansible.builtin.import_playbook: vclusters.yml
  tags: vclusters
