# applies all Kubernetes manifests in the "manifests" directory
# IMPORTANT: manifests must specify namespaces to install into
---
- name: Create resources on RKE cluster
  hosts: "{{ rke_control_plane_host }}"
  gather_facts: false
  vars_files:
    - vars/kubernetes.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
  tasks:
    - name: Apply Kubernetes manifests
      vars:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fileglob_lookup.html
        # https://docs.ansible.com/ansible/latest/plugins/lookup.html#forcing-lookups-to-return-lists-query-and-wantlist-true
        manifests: "{{ query('ansible.builtin.fileglob', 'manifests/*.y*ml') }}"
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
      kubernetes.core.k8s:
        kubeconfig: "{{ rke_kubeconfig }}"
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html
        definition: "{{ lookup('ansible.builtin.file', item) }}"
        validate:
          fail_on_error: false
        state: present
        apply: true
        wait: true
      loop: "{{ manifests }}"
      loop_control:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/basename_filter.html
        label: "{{ item | ansible.builtin.basename }}"
      timeout: 300
  any_errors_fatal: true
