# https://metacontroller.github.io/metacontroller
---
- name: Install Kubernetes Metacontroller
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/metacontroller.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/monitoring/stackready.yml
      when: monitoring_stack_ready is not defined
  tasks:
    # https://metacontroller.github.io/metacontroller/guide/helm-install.html
    - name: Install Metacontroller Helm chart
      vars:
        metrics_port: "{{ metacontroller_chart_values.service.ports[0].port }}"
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_lookup.html
        smon_manifest: "{{ lookup('ansible.builtin.template',
          template_dir ~ '/monitoring/smons/metacontroller.yaml.j2') }}"

        # === Inputs ===
        tmpdir_name: metacontroller
        chart_ref: "{{ metacontroller_chart_oci_url }}"
        chart_ver: "{{ metacontroller_chart_version }}"
        release: "{{ metacontroller_release_name }}"
        release_ns: "{{ metacontroller_namespace }}"
        values: "{{ metacontroller_chart_values }}"

        patches:
          json_patches:
            # add missing serviceName and pod metrics port to
            # StatefulSet and adjust container probe timeouts
            # (use JSON patch instead of merge patch because
            # container is also renamed, and strategic merge
            # patch uses name as selector key)
            - target:
                group: apps
                version: v1
                kind: StatefulSet
                name: "{{ metacontroller_release_name }}"
                namespace: "{{ metacontroller_namespace }}"
              patch:
                - op: replace
                  path: /spec/template/spec/containers/0/name
                  value: metacontroller
                - op: add
                  path: /spec/template/spec/containers/0/ports
                  value:
                    - name: metrics
                      containerPort: "{{ metrics_port }}"
                - op: add
                  path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
                  value: 3
                - op: add
                  path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
                  value: 3
                - op: add
                  path: /spec/serviceName
                  value: "{{ metacontroller_release_name }}"
                - op: add
                  path: /spec/revisionHistoryLimit
                  value: 2

        extras: # adopt extra resources into Helm release
          - "{{ smon_manifest | from_yaml if prometheus_crds_installed else [] }}"
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml
