# https://metallb.io/
# https://metallb.io/concepts
# https://metallb.io/concepts/bgp
---
- name: Install MetalLB on RKE cluster
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/metallb.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/monitoring/stackready.yml
      when: monitoring_stack_ready is undefined

    - name: Does IPAddressPool CRD exist?
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        # name must be in plural form!
        name: ipaddresspools.metallb.io
      register: crd_info
  tasks:
    - name: Create MetalLB speaker secret
      vars:
        secret_name: "{{ metallb_secrets['speaker'] }}"
        secret_data:
          # metallb_secret: {vault.yml}
          # key must be "secretkey" due
          # to bug in Bitnami Helm chart:
          # https://github.com/bitnami/charts/issues/36271
          secretkey: "{{ metallb_secret }}"
        secret_ns: "{{ metallb_namespace }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/generic.yml

    - name: Install MetalLB Helm chart
      vars:
        repo_name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        chart_ref: metallb
        chart_ver: "{{ metallb_chart_version }}"
        release: "{{ metallb_release_name }}"
        release_ns: "{{ metallb_namespace }}"
        values: "{{ metallb_chart_values }}"

        extras: # adopt extra resources into Helm release
          - v1 Secret {{ metallb_secrets['speaker'] }}
          - "{{ metallb_config_crs if crd_info.resources is truthy else [] }}"
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml

    - name: Create MetalLB config CRs
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        namespace: "{{ metallb_namespace }}"
        definition: "{{ item }}"
        state: present
      loop: "{{ metallb_config_crs }}"
      loop_control:
        label: "{{ item.kind }}"
      when: crd_info.resources is falsy
