# https://jonathangazeley.com/2025/02/11/intel-gpu-acceleration-on-kubernetes
# https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus
#
# GPU detection on our nodes requires the following steps:
# 1. install linux-modules-extra-<kernel> package on nodes: Intel i915 driver
# 2. enable GPU passthrough on XCP-ng hosts: xen-pciback.hide=(0000:00:02.0)
# 3. assign PCI passthrough to select nodes: other-config:pci=0/0000:00:02.0
#    (steps 2 and 3 are performed by the "homelab-xcp" Ansible project)
---
# https://kubernetes-sigs.github.io/node-feature-discovery
# https://kubernetes-sigs.github.io/node-feature-discovery/stable/deployment/helm.html
- name: Install Node Feature Discovery
  tags: install
  hosts: &hosts
    - "{{ k3s_control_plane_host }}"
    - "{{ rke_control_plane_host }}"
  vars_files: &vars_files
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/nodefeatures.yml
  vars: &vars
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ternary_filter.html
    cluster: "{{ (inventory_hostname in groups['k3s_cluster']) | ternary('k3s','rke') }}"
    kubeconfig: "{{ vars[cluster ~'_kubeconfig'] }}"
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/monitoring/stackready.yml
      when: monitoring_stack_ready is undefined

    - name: Does NodeFeatureRule CRD exist?
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        # name must be in plural form!
        name: nodefeaturerules.nfd.k8s-sigs.io
      register: crd_info
  tasks:
    - name: Install Node Feature Discovery Helm chart
      vars:
        rules: |
          {% set rules = [] %}
          {% for rule in additional_node_feature_rules %}
          {%   if rule.url is defined %}
          {#     https://docs.ansible.com/ansible/latest/collections/ansible/builtin/url_lookup.html #}
          {%     set def = lookup('ansible.builtin.url', rule.url, split_lines=false) | from_yaml %}
          {%     set   _ = rules.append({
                   'name': rule.name,
                   'def':  def,
                 }) %}
          {%   else %}
          {%     set _ = rules.append(rule) %}
          {%   endif %}
          {% endfor  %}
          {{ rules   }}
      block:
        - name: Install Node Feature Discovery Helm chart
          vars:
            repo_name: nfd
            repo_url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
            chart_ref: node-feature-discovery
            chart_ver: "{{ nfd_chart_version }}"
            release: "{{ nfd_release_name }}"
            release_ns: "{{ nfd_namespace }}"
            values: "{{ nfd_chart_values }}"

            extras: # adopt extra resources into Helm release
              - "{{ rules | map(attribute='def') if crd_info.resources is truthy else [] }}"
          ansible.builtin.include_tasks: tasks/helm/helmfile.yml

        # this step is what would add vendor-specific labels,
        # like "intel.feature.node.kubernetes.io/gpu=true" or
        # "feature.node.kubernetes.io/pci-10de.present=true"
        - name: Deploy additional node feature rules
          # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig   }}"
            definition: "{{ item.def     }}"
            namespace: "{{ nfd_namespace }}"
            state: present
            apply: true
          loop: "{{ rules }}"
          loop_control:
            label: "{{ item.name }}"
          when: crd_info.resources is falsy

# https://intel.github.io/intel-device-plugins-for-kubernetes
# https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/operator/README.html#installation
- name: Install Intel Device Plugins
  tags: plugins
  hosts: *hosts
  vars_files: *vars_files
  vars: *vars
  pre_tasks:
    - name: Does GpuDevicePlugin CRD exist?
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        # name must be in plural form!
        name: gpudeviceplugins.deviceplugin.intel.com
      register: crd_info
  tasks:
    - name: Install Intel Device Plugins Helm chart
      vars:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dict2items_filter.html
        plugins: "{{ intel_device_plugin_crs | ansible.builtin.dict2items(
          key_name='type', value_name='def') }}"
      block:
        - name: Install Intel Device Plugins Helm chart
          vars:
            repo_name: intel
            repo_url: https://intel.github.io/helm-charts
            chart_ref: intel-device-plugins-operator
            chart_ver: "{{ intel_dp_operator_chart_version }}"
            release: "{{ intel_dp_operator_release_name }}"
            release_ns: "{{ intel_device_plugins_namespace }}"
            values: "{{ intel_dp_operator_chart_values }}"

            patches:
              merge_patches:
                # default 1s timeout for readiness and liveness
                # probes are too optimistic for our environment
                - apiVersion: apps/v1
                  kind: Deployment
                  metadata:
                    name: inteldeviceplugins-controller-manager
                    namespace: "{{ intel_device_plugins_namespace }}"
                  spec:
                    template:
                      spec:
                        containers:
                          - name: manager
                            readinessProbe: &probe
                              timeoutSeconds: 5
                            livenessProbe: *probe

            extras: # adopt extra resources into Helm release
              - "{{ plugins | map(attribute='def') if crd_info.resources is truthy else [] }}"
          ansible.builtin.include_tasks: tasks/helm/helmfile.yml

        - name: Deploy Intel Device Plugin CRs
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig }}"
            definition: "{{ item.def   }}"
            namespace: "{{ intel_device_plugins_namespace }}"
            state: present
            apply: true
          loop: "{{ plugins }}"
          loop_control:
            label: "{{ item.type }}"
          when: crd_info.resources is falsy
