# https://github.com/ollama/ollama
# https://ollama.com/blog/embedding-models
---
# https://github.com/intel/ipex-llm
# https://github.com/intel/ipex-llm/tree/main/docs/mddocs/Quickstart/ollama_portable_zip_quickstart.md
- name: Build Ollama image with IPEX-LLM
  tags: build
  hosts: localhost
  vars_files: &vars_files
    - vars/kubernetes.yml
    - vars/metallb.yml
    - vars/storage.yml
    - vars/ollama.yml
  tasks:
    - name: Build Ollama image with IPEX-LLM
      when: use_ollama_chart_by == 'cowboysysop'
      block:
        - name: Include vars/ollama.cowboysysop.yml
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_vars_module.html
          ansible.builtin.include_vars: vars/ollama.cowboysysop.yml

        - name: Build image and push to Harbor
          vars:
            context_dir: files/ollama
            image_name: "{{ ollama_chart_values.image.repository }}"
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
          ansible.builtin.include_tasks: tasks/oci/build.yml

- name: Install Ollama on RKE cluster
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files: *vars_files
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    vars_file: vars/ollama.{{ use_ollama_chart_by }}.yml
    kubeconfig: "{{ rke_kubeconfig }}"
  pre_tasks:
    - name: Include {{ vars_file }}
      ansible.builtin.include_vars: "{{ vars_file }}"
  tasks:
    - name: Create Ollama ingress secret
      vars:
        secret_name: "{{ ollama_secrets['ingress'] }}"
        secret_ns: "{{ ollama_namespace }}"
        cert_name: ollama
        sans: "{{ [ollama_fqdn] }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Install Ollama Helm chart
      vars:
        repo_name: "{{ use_ollama_chart_by }}"
        repo_url: "{{ ollama_chart_repo_url }}"
        chart_ref: ollama
        chart_ver: "{{ ollama_chart_version }}"
        release: "{{ ollama_release_name }}"
        release_ns: "{{ ollama_namespace }}"
        values: "{{ ollama_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ ollama_secrets['ingress'] }}
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml
