---
- name: Install required packages
  tags: install
  hosts: k8s_hosts
  vars_files:
    - vars/packages.yml
  tasks:
    - name: Install required Apt packages
      become: true
      block:
        - name: Configure Apt package sources
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
          ansible.builtin.include_tasks: tasks/packages/apt/sources.yml
          loop: "{{ apt_sources }}"
          loop_control:
            loop_var: source
            label: "{{ source.sources.file }}"

        - name: Add Apt package repositories
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
          ansible.builtin.apt_repository:
            repo: "{{ item[1] }}"
            state: present
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/subelements_filter.html
          loop: "{{ apt_repositories | ansible.builtin.subelements('repos') }}"
          loop_control:
            label: "{{ item[0].hosts | join(',') ~'|'~ item[1] }}"
          when: inventory_hostname in item[0].hosts
          # task could fail due to normal Apt updates
          # that hold lock, so retry until successful
          retries: 3
          delay: 5

        - name: Install required Apt packages
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
          ansible.builtin.apt:
            name: "{{ item.packages }}"
            state: present
            update_cache: true
            force_apt_get: true
            install_recommends: false
          loop: "{{ apt_packages }}"
          loop_control:
            label: "{{ item.hosts | join(',') ~'|...' }}"
          when: inventory_hostname in item.hosts
          retries: 3
          delay: 5

        - name: Clean downloaded Apt packages
          ansible.builtin.apt:
            autoremove: true
            clean: true
            purge: true
          # otherwise always
          # reports "changed"
          changed_when: false
          retries: 3
          delay: 5

        - name: Configure installed packages
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
          ansible.builtin.shell: |
            set -eo pipefail
            rc=9

            # set binaries setuid bit so these
            # commands can be run without sudo
            cmds=(
              lsof
              iotop
            )
            for cmd in "${cmds[@]}"; do
              bin=$(realpath $(command -v $cmd))
              [[ "$(stat -c %A $bin)"  == *s* ]] || {
                chmod u+s $bin
                rc=0
              }
            done
            exit $rc
          args:
            executable: /bin/bash
          register: config_pkgs
          changed_when: config_pkgs.rc == 0
          failed_when: config_pkgs.rc not in [0,9]

    # create virtualenv in user's home directory
    - name: Install required Pip packages
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: present
        virtualenv: "{{ ansible_user_virtualenv }}"

    - name: Create /etc/profile.d/venv.sh
      become: true
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      ansible.builtin.copy:
        dest: /etc/profile.d/venv.sh
        content: |
          export PATH="$HOME/.venv/bin:$PATH"
        mode: "0644"

    # plugins are installed in the user's home
    # directory under .local/share/helm/plugins
    - name: Install useful Helm plugins
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_plugin_module.html
      kubernetes.core.helm_plugin:
        plugin_name: "{{ item.name | default(omit) }}"
        plugin_path: "{{ item.path | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ helm_plugins }}"

- name: Install apps from GitHub releases
  tags: github
  hosts: k8s_hosts
  become: true
  tasks:
    - name: Install app using GitHub release
      vars:
        base_dir: "{{ template_dir }}/packages/install"
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fileglob_lookup.html
        # https://docs.ansible.com/ansible/latest/plugins/lookup.html#forcing-lookups-to-return-lists-query-and-wantlist-true
        scripts: "{{ query('ansible.builtin.fileglob', base_dir ~ '/*.sh*') |
          map('ansible.builtin.basename') | select('search', '^[^.].+') }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_lookup.html
      ansible.builtin.shell: "{{ lookup('ansible.builtin.template', base_dir ~'/'~ item) }}"
      args:
        executable: /bin/bash
      # names not sorted by default
      loop: "{{ scripts | sort }}"
      loop_control:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/regex_replace_filter.html
        label: "{{ item | ansible.builtin.regex_replace('\\.sh(\\.j2)?$', '') }}"
      register: install_app
      changed_when: install_app.rc == 0
      failed_when: install_app.rc not in [0,9]
      retries: 3
      delay: 5
