# https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
---
- name: Install PostgreSQL on RKE cluster
  hosts: "{{ rke_control_plane_host }}"
  gather_facts: false
  vars_files:
    - vars/kubernetes.yml
    - vars/storage.yml
    - vars/monitoring.yml
    - vars/keycloak.yml
    - vars/postgresql.yml
  vars:
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ postgresql_namespace }}"
    create_ns: false
    release: "{{ postgresql_release_name }}"
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/monitoring/stackready.yml
      when: monitoring_stack_ready is not defined
  tasks:
    - name: Create PostgreSQL node secret
      vars:
        secret_name: "{{ postgresql_secrets['node-tls'] }}"
        create_ns: true
        cert_name: postgresql-node
        sans_:
          - "{{ postgresql_fqdns }}"
          - "*.{{ postgresql_namespace }}.svc.cluster.local"
          - "*.{{ postgresql_namespace }}.svc"
          - "{{ postgresql_lb_ip }}"
        sans: "{{ sans_ | flatten }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Create Pgpool exporter secret
      ansible.builtin.include_tasks: tasks/monitoring/scraper.yml

    # https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
    - name: Install PostgreSQL HA Helm chart
      vars:
        # required kubernetes>=24.2 package only in user virtualenv
        ansible_python_interpreter: "{{ venv_python_interpreter }}"
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        chart_repo_url: https://charts.bitnami.com/bitnami
        chart_ref: postgresql-ha
        chart_version: "{{ postgresql_chart_version }}"
        release_name: "{{ postgresql_release_name }}"
        release_namespace: "{{ postgresql_namespace }}"
        release_values: "{{ postgresql_chart_values }}"
        atomic: true
        wait: true
        wait_timeout: 10m0s # requires wait=true
      timeout: 1800

    - name: Import Grafana dashboards
      vars:
        dashboards: "{{ postgresql_grafana_dashboards }}"
      ansible.builtin.include_tasks: tasks/grafana/dashboards.yml
      when: grafana_api_server_online | default(true)
  any_errors_fatal: true
