# https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
---
- name: Install PostgreSQL on RKE cluster
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/metallb.yml
    - vars/storage.yml
    - vars/monitoring.yml
    - vars/postgresql.yml
    # these are only needed for
    # their *_db_user variables
    - vars/keycloak.yml
    - vars/awx.yml
    - vars/gitlab.yml
    - vars/litellm.yml
    - vars/openwebui.yml
    - vars/flowise.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ postgresql_namespace }}"
    create_ns: false
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/monitoring/stackready.yml
      when: monitoring_stack_ready is undefined
  tasks:
    - name: Create PostgreSQL node secret
      vars:
        secret_name: "{{ postgresql_secrets['node-tls'] }}"
        create_ns: true
        cert_name: postgresql-node
        sans_:
          - postgresql-node
          - "{{ postgresql_fqdns }}"
          - "*.{{ postgresql_namespace }}.svc.{{ cluster_domain }}"
          - "*.{{ postgresql_namespace }}.svc"
          - "{{ metallb_vips['postgresql'] }}"
        sans: "{{ sans_ | flatten }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Create Pgpool exporter secret
      ansible.builtin.include_tasks: tasks/monitoring/scraper.yml

    - name: Install PostgreSQL HA Helm chart
      vars:
        repo_name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        chart_ref: postgresql-ha
        chart_ver: "{{ postgresql_chart_version }}"
        release: "{{ postgresql_release_name }}"
        release_ns: "{{ postgresql_namespace }}"
        values: "{{ postgresql_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ postgresql_secrets['node-tls'] }}
          - cert-manager.io/v1 Certificate {{ monitoring_secrets['scraper']  }}

        wait_timeout: 600
        task_timeout: 1800
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml

- name: Configure PostgreSQL dashboards
  tags: dashboards
  hosts: localhost
  vars_files:
    - vars/postgresql.yml
  tasks:
    - name: Import Grafana dashboards
      vars:
        dashboards: "{{ postgresql_grafana_dashboards }}"
      ansible.builtin.include_tasks: tasks/grafana/dashboards.yml
      when: grafana_api_server_online | default(true)
