# https://github.com/pyrra-dev/pyrra
#
# UNINSTALLATION STEPS:
# delete SLO CRs first:
# kubectl get -A slo -o jsonpath='{range .items[*]}{.metadata.namespace} {.metadata.name}{"\n"}{end}' | \
#   xargs -L1 -r kubectl delete slo -n
# helm delete -n pyrra pyrra
---
- name: Install Pyrra SLO management
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files: &vars_files
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/thanos.yml
    - vars/pyrra.yml
  vars: &vars
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ pyrra_namespace }}"
    create_ns: false
  tasks:
    - name: Create Pyrra ingress secret
      vars:
        secret_name: "{{ pyrra_secrets['ingress'] }}"
        create_ns: true
        cert_name: pyrra-ingress
        sans: "{{ pyrra_fqdns }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Create credentials secret
      vars:
        secret_name: "{{ pyrra_secrets['creds'] }}"
        secret_data:
          thanos-pass: "{{ monitoring_pass }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/generic.yml

    - name: Install Pyrra Helm chart
      vars:
        repo_name: pyrra
        repo_url: https://pyrra-dev.github.io/helm-charts
        chart_ref: pyrra
        chart_ver: "{{ pyrra_chart_version }}"
        release: "{{ pyrra_release_name }}"
        release_ns: "{{ pyrra_namespace }}"
        values: "{{ pyrra_chart_values }}"

        patches:
          # chart doesn't currently support extra
          # volumes and mounts, so add as patches
          merge_patches:
            - apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: "{{ pyrra_release_name }}"
              spec:
                template:
                  spec:
                    containers:
                      - name: pyrra
                        env: "{{ values.extraApiEnvs }}"
                        volumeMounts: "{{ values.extraVolumeMounts }}"
                    volumes: "{{ values.extraVolumes }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ pyrra_secrets['ingress'] }}
          - v1 Secret {{ pyrra_secrets['creds'] }}
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml

- name: Create ServiceLevelObjectives
  tags: slos
  hosts: "{{ rke_control_plane_host }}"
  vars_files: *vars_files
  vars: *vars
  pre_tasks:
    - name: Clear platform_slos fact
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        platform_slos: []
  tasks:
    # https://github.com/pyrra-dev/pyrra/tree/main/examples/kubernetes/manifests/slos
    - name: Get list of example SLOs
      vars:
        repo: pyrra-dev/pyrra
        repo_dir: contents/examples/kubernetes/manifests/slos
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ repo }}/{{ repo_dir }}?ref=main
        return_content: true
      register: example_slos

    - name: Add SLO to platform_slos
      vars:
        patches:
          - search: job="kube-dns"
            replace: job="coredns"
          - search: job="prometheus-k8s"
            replace: job="{{ monitoring_release_name }}-prometheus"
          - search: job="prometheus-operator"
            replace: job="{{ monitoring_release_name }}-operator"
        file_urls: |
          {{ example_slos.json |
             selectattr('type', '==',     'file') |
             selectattr('name', 'search', '^slo-.+\.yaml$') |
             map(attribute='download_url') }}
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/url_lookup.html
        manifest: "{{ lookup('ansible.builtin.url', item, split_lines=false) }}"
        resource: |
          {# use namespace() to create a scoped object #}
          {# https://jinja.palletsprojects.com/en/stable/templates#assignments #}
          {% set ns = namespace(yaml=manifest) %}
          {% for patch in patches %}
          {%   set ns.yaml = ns.yaml | replace(patch.search,
                                               patch.replace) %}
          {% endfor %}
          {{ ns.yaml | from_yaml }}
        res_name: "{{ resource.metadata.name }}"
        # remove fixed namespace and
        # update ruleSelector labels
        definition: |
          {% set _ = resource.update({
               'metadata': {
                 'name':   res_name,
                 'labels': monitoring_selector_labels,
               },
             }) %}
          {{ resource }}
      ansible.builtin.set_fact:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_lookup.html
        platform_slos: "{{ platform_slos + [definition] }}"
      loop: "{{ file_urls }}"
      loop_control:
        label: "{{ res_name }}"

    - name: Add SLO to platform_slos
      # services should attach SLOs
      # to their own Helm releases
      when: false
      vars:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fileglob_lookup.html
        # https://docs.ansible.com/ansible/latest/plugins/lookup.html#forcing-lookups-to-return-lists-query-and-wantlist-true
        manifests: "{{ query('ansible.builtin.fileglob',
          template_dir ~ '/monitoring/slos/*.yaml*') }}"
      ansible.builtin.set_fact:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/from_yaml_all_filter.html
        platform_slos: "{{ platform_slos + lookup('ansible.builtin.template', item) | from_yaml_all }}"
      loop: "{{ manifests }}"
      loop_control:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/basename_filter.html
        label: "{{ item | ansible.builtin.basename | regex_replace('\\.yaml(\\.j2)?', '') }}"

    - name: Create all platform SLOs
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        namespace: "{{ monitoring_namespace }}"
        definition: "{{ platform_slos }}"
        state: present
        apply: true
