# https://thanos.io/tip/thanos/quick-tutorial.md
---
- name: Install Thanos component suite
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/storage.yml
    - vars/minio.yml
    - vars/valkey.yml
    - vars/monitoring.yml
    - vars/thanos.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ monitoring_namespace }}"
    create_ns: false
  tasks:
    - name: Create Thanos ingress secret
      vars:
        secret_name: "{{ thanos_secrets[item.name] }}"
        cert_name: thanos-{{ item.name }}-ingress
        sans_:
          - thanos
          - "{{ item.sans | default([]) }}"
          - "{{ thanos_fqdns[item.name] }}"
          - "*.{{ monitoring_namespace }}.svc.{{ cluster_domain }}"
          - "*.{{ monitoring_namespace }}.svc"
        sans: "{{ sans_ | flatten }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml
      loop:
        - name: query
          sans: # thanos.fourteeners.local is for Query
            - "{{ monitoring_fqdns['thanos'] | last }}"
        - name: rule
        - name: store
        - name: bucket
        - name: compact
      loop_control:
        label: "{{ item.name }}"

    - name: Install Thanos Helm chart
      vars:
        repo_name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        chart_ref: thanos
        chart_ver: "{{ thanos_chart_version }}"
        release: "{{ thanos_release_name }}"
        release_ns: "{{ monitoring_namespace }}"
        values: "{{ thanos_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate thanos-query-ingress
          - cert-manager.io/v1 Certificate thanos-rule-ingress
          - cert-manager.io/v1 Certificate thanos-store-ingress
          - cert-manager.io/v1 Certificate thanos-bucket-ingress
          - cert-manager.io/v1 Certificate thanos-compact-ingress
          # Thanos tripper ConfigMap for Thanos Query Frontend
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: thanos-query-frontend-tripper
            data: "{{ thanos_tripper_config }}"
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml
