# https://valkey.io/topics/cluster-tutorial
# https://blog.enapi.com/valkey-clusters-in-kubernetes-a-comprehensive-guide-94994d0a8ebb
# https://techdocs.broadcom.com/us/en/vmware-tanzu/application-catalog/tanzu-application-catalog/services/tac-doc/apps-apps-valkey-cluster-index.html
---
- name: Install Valkey on RKE cluster
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/metallb.yml
    - vars/storage.yml
    - vars/monitoring.yml
    - vars/valkey.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ valkey_namespace }}"
    create_ns: false
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/monitoring/stackready.yml
      when: monitoring_stack_ready is not defined
  tasks:
    - name: Create Valkey node secret
      vars:
        secret_name: "{{ valkey_secrets['node-tls'] }}"
        create_ns: true
        cert_name: valkey-node
        sans_:
          - valkey-node
          - "{{ valkey_fqdns }}"
          - "*.{{ valkey_namespace }}.svc.{{ cluster_domain }}"
          - "*.{{ valkey_namespace }}.svc"
          - "{{ valkey_lb_ips }}"
        sans: "{{ sans_ | flatten }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Create Valkey password secret
      vars:
        key: "{{ valkey_chart_values.existingSecretPasswordKey }}"
        secret_name: "{{ valkey_secrets['password'] }}"
        secret_data: "{{ { key: valkey_pass } }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/generic.yml

    - name: Install Valkey cluster Helm chart
      vars:
        repo_name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        chart_ref: valkey-cluster
        chart_ver: "{{ valkey_chart_version }}"
        release: "{{ valkey_release_name }}"
        release_ns: "{{ valkey_namespace }}"
        values: "{{ valkey_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ valkey_secrets['node-tls'] }}
          - v1 Secret {{ valkey_secrets['password'] }}
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml

- name: Configure Valkey dashboards
  tags: dashboards
  hosts: localhost
  vars_files:
    - vars/valkey.yml
  tasks:
    - name: Import Grafana dashboards
      vars:
        dashboards: "{{ valkey_grafana_dashboards }}"
      ansible.builtin.include_tasks: tasks/grafana/dashboards.yml
      when: grafana_api_server_online | default(true)
