# https://developer.hashicorp.com/vault/docs
# https://developer.hashicorp.com/vault/docs/deploy/kubernetes
# https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-raft-deployment-guide
---
- name: Install Vault on RKE cluster
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/storage.yml
    - vars/vault.yml
  vars: &vars
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ vault_namespace }}"
    create_ns: false
  tasks:
    - name: Create Vault node secret
      vars:
        secret_name: "{{ vault_secrets['node-tls'] }}"
        create_ns: true
        cert_name: vault-node
        sans_:
          - vault-node
          - "{{ vault_fqdn }}"
          - "*.{{ vault_namespace }}.svc.{{ cluster_domain }}"
          - "*.{{ vault_namespace }}.svc"
          - |
            {% set sans = [] %}
            {% for i in range(0, vault_chart_values.server.ha.replicas) %}
            {%   set _ = sans.append(vault_release_name ~'-'~ i ~'.vault-internal') %}
            {% endfor %}
            {{ sans   }}
          - 127.0.0.1
        sans: "{{ sans_ | flatten }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: tasks/k8s/secrets/tls.step.yml

    - name: Create monitoring scraper secret
      ansible.builtin.include_tasks: tasks/monitoring/scraper.yml

    - name: Install Vault Helm chart
      vars:
        repo_name: hashicorp
        repo_url: https://helm.releases.hashicorp.com
        chart_ref: vault
        chart_ver: "{{ vault_chart_version }}"
        release: "{{ vault_release_name }}"
        release_ns: "{{ vault_namespace }}"
        values: "{{ vault_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ vault_secrets['node-tls']     }}
          - cert-manager.io/v1 Certificate {{ monitoring_secrets['scraper'] }}
          - v1 Secret {{ vault_secrets['unseal'] }} ? # populated by bootstrap
          - | # ServiceAccount/Role/RoleBinding/Job
            {{ lookup('ansible.builtin.template', template_dir ~ '/vault/bootstrap.yaml.j2')
               |  split('---') | select('search', 'apiVersion:') | map('from_yaml') }}
      ansible.builtin.include_tasks: tasks/helm/helmfile.yml

    # Vault will be bootstrapped (initialized and unsealed)
    # by Helm post-install hook, but if a pod is restarted
    # after bootstrap, it must be unsealed again manually:
    #
    # if unseal keys in `vault-unseal-keys` Secret haven't
    # been redacted, then run the command below locally to
    # generate  `vault operator unseal` commands to run in
    # the pod:
    #
    # kubectl get secrets -n vault vault-unseal-keys -o yaml | \
    #   yq '.data.unsealKeys | @base64d | from_yaml | .[] |
    #      "vault operator unseal \"\(.)\""' | \
    #   shuf -n 3 | pbcopy

# https://developer.hashicorp.com/vault/install
- name: Install Vault CLI tool
  tags: cli
  hosts: rke_cluster
  vars_files:
    - vars/vault.yml
  tasks:
    # NOTE: this Apt install requires that the HashiCorp
    # GPG keyring and Apt sources list be pre-configured
    # (see apt_sources[] definition in vars/packages.yml)
    - name: Install Vault CLI tool
      become: true
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
      ansible.builtin.apt:
        name: vault
        state: present
        update_cache: true
        force_apt_get: true
        install_recommends: false
      retries: 3
      delay: 5

    - name: Log in to Vault by CLI
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        # restart Bash and load .bash_aliases
        exec /bin/bash -l <<'EOT'
        . .bash_aliases
        set -o pipefail

        token=$(kubectl get secret {{ vault_secrets['unseal'] }} \
             -n {{ vault_namespace }} -o json | \
          jq -r '.data.rootToken // "" | @base64d')
        [ "$token" ] || {
          echo >&2 "Error: could not get Vault root token"
          exit 1
        }
        [[ "$token" ==  redacted...*  || \
           "$token" == "$VAULT_TOKEN" ]] && exit 9 # no change

        # BASH_ENV_DIR is set in .bash_aliases
        cat <<EOF > "$BASH_ENV_DIR/vault.env"
        VAULT_ADDR="{{ vault_url }}"
        VAULT_TOKEN="$token"
        VAULT_FORMAT="yaml"
        EOF
        EOT
      register: config_cli
      changed_when: config_cli.rc == 0
      failed_when: config_cli.rc not in [0,9]

# https://developer.hashicorp.com/vault/docs/concepts/policies
# https://developer.hashicorp.com/vault/docs/auth/kubernetes
# https://developer.hashicorp.com/vault/docs/auth/userpass
- name: Configure Vault authentication
  tags: auth
  hosts: rke_any
  vars_files:
    - vars/kubernetes.yml
    - vars/externalsecrets.yml
    - vars/vault.yml
  pre_tasks:
    - name: Wait for Vault to be ready
      vars:
        kubeconfig: "{{ rke_kubeconfig }}"
        res_kind: StatefulSet
        res_name: "{{ vault_release_name }}"
        res_ns: "{{ vault_namespace }}"
      ansible.builtin.include_tasks: tasks/k8s/waitready.yml
  tasks:
    - name: Create policies/users/roles
      ansible.builtin.shell: |
        # set VAULT_ADDR
        . .bash_aliases
        set -eo pipefail

        # get list of enabled auth methods:
        methods="$(vault auth list -format=json | jq -r 'keys[]')" || true

        # first, enable Kubernetes auth in order to
        # create role for External Secrets Operator
        grep -q '^kubernetes/' <<< "$methods" || {
          echo >&2 "Enabling Kubernetes auth"
          # https://developer.hashicorp.com/vault/docs/auth/kubernetes#configuration
          vault auth enable kubernetes

          # https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#configure-method
          vault write auth/kubernetes/config \
            kubernetes_host="{{ kube_api_url }}"
        }
        grep -q '^userpass/' <<< "$methods" || {
          echo >&2 "Enabling Userpass auth"
          vault auth enable userpass

          # https://support.hashicorp.com/hc/en-us/articles/360001922527-Configuring-a-Default-UI-Auth-Method
          # https://developer.hashicorp.com/vault/api-docs/system/auth#tune-auth-method
          vault write sys/auth/userpass/tune listing_visibility=unauth
        }

        # get list of existing policies:
        policies="$(vault policy list -format=json | jq -r '.[]')" || true
        {% for name, stanzas in vault_policies.items() %}

        grep -q '^{{ name }}$' <<< "$policies" || {
          echo >&2 "Creating policy: {{ name  }}"
          vault policy write {{ name }} - <<'EOT'
        {%   for policy in stanzas %}
        {%     set capabilities = policy.capabilities | to_json(separators=[',',':']) %}
        path "{{ policy.path }}" {
          capabilities = {{ capabilities }}
        }
        {%   endfor %}
        EOT
          rc=0
        }
        {% endfor %}

        # get list of existing users:
        users="$(vault list -format=json auth/userpass/users | jq -r '.[]')" || true

        {%- for name, user in vault_users.items() +%}
        {# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/union_filter.html #}
        {% set policies = user.policies | default([]) |
                  ansible.builtin.union(['default'])  |
                  join(',') %}

        grep -q '^{{ name }}$' <<< "$users" || {
          echo >&2 "Creating user: {{ name  }}"
          vault write auth/userpass/users/{{ name }} \
            password='{{ user.password }}' \
            policies='{{      policies }}'
          rc=0
        }
        {% endfor %}

        # get list of existing roles:
        roles="$(vault list -format=json auth/kubernetes/role | jq -r '.[]')" || true
        {% for name, role in vault_roles.items() %}
        {%   set sa_names      = [role.sa_names]      | flatten | join(',') %}
        {%   set sa_namespaces = [role.sa_namespaces] | flatten | join(',') %}

        grep -q '^{{ name }}$' <<< "$roles" || {
          echo >&2 "Creating role: {{ name  }}"

          # https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#create-update-role
          vault write auth/kubernetes/role/{{  name  }}  \
            bound_service_account_names='{{ sa_names }}' \
            bound_service_account_namespaces='{{ sa_namespaces }}' \
        {%   if role.audience is defined %}
            audience='{{ role.audience   }}' \
        {%   endif %}
        {%   for key, value in role.items() %}
        {%     if key.startswith('token_')  %}
            {{ key }}='{{ [value] | flatten | join(',') }}' \
        {%     endif %}
        {%   endfor  %}
        ; rc=0
        }
        {% endfor %}
        set +e; exit ${rc-9}
      args:
        executable: /bin/bash
      register: vault_create
      changed_when: vault_create.rc == 0
      failed_when: vault_create.rc not in [0,9]

- name: Populate Vault with secret data
  tags: data
  hosts: rke_any
  vars_files:
    - vars/vault.yml
    # vault_secrets_data.*
    - vars/vault.secrets.yml
  tasks:
    - name: Write secrets data to KV mounts
      ansible.builtin.shell: |
        # set VAULT_ADDR
        . .bash_aliases
        set -eo pipefail

        # get list of KV mounts:
        mounts="$(vault secrets list -format=json | \
          jq -r 'to_entries[] | select(.value.type == "kv") | .key')"
        {% for name in vault_kv_mounts.values() %}

        grep -q '^{{ name }}/' <<< "$mounts" || {
          echo  >&2 "Creating mount: {{ name }}"
          vault secrets enable -path={{ name }} -version=2 kv
          vault write {{ name }}/config \
            max-versions=1 \
            delete-version-after=0s \
            cas-required=false
          rc=0
        }
        {% endfor %}

        # vault_secrets_data is a dictionary
        # where top-level keys are KV mounts,
        # second-level keys are secret paths,
        # third-level are individual KV pairs

        {%- for mount, secrets in vault_secrets_data.items() +%}
        {%   if mount in vault_kv_mounts.values() %}
        {%     for path, pairs in secrets.items() %}

        json_="$(vault kv get -format=json \
          {{ mount }}/{{ path }} 2> /dev/null | \
             jq -cM '.data.data')" || true
        json="$(cat <<'JSON'
        {{ pairs | to_json(separators=[',',':']) }}
        JSON
        )"
        if [ "$json_" != "$json" ]; then
          echo >&2  "Writing secret: {{ mount }}/{{ path }}"
          vault kv put -format=table {{ mount }}/{{ path }} \
             - <<< "$json" | sed -n '2p' # show second line
          rc=0
        fi
        {%     endfor %}
        {%   endif    %}
        {% endfor     %}
        set +e; exit ${rc-9}
      args:
        executable: /bin/bash
      register: vault_data
      changed_when: vault_data.rc == 0
      failed_when: vault_data.rc not in [0,9]

    # prepare SOPS to be used by Argo CD:
    # https://github.com/getsops/sops#27encrypting-using-hashicorp-vault
    - name: Create transit keys for SOPS
      ansible.builtin.shell: |
        # set VAULT_ADDR
        . .bash_aliases
        set -eo pipefail

        # get list of transit mounts:
        mounts="$(vault secrets list -format=json | \
          jq -r 'to_entries[] | select(.value.type == "transit") | .key')"
        grep -q '^sops/' <<< "$mounts" || {
          echo >&2 "Creating transit mount: sops/"
          vault secrets enable -path=sops transit
          rc=0
        }

        # get list of existing keys:
        keys="$(vault list -format=json sops/keys | jq -r '.[]')" || true
        grep -q '^default$' <<< "$keys" || {
          echo >&2 "Importing aes256 key: default"
          # https://developer.hashicorp.com/vault/docs/secrets/transit#key-types
          vault transit import sops/keys/default \
            {{ sops_encryption_key }} type=aes256-gcm96
          rc=0
        }
        set +e; exit ${rc-9}
      args:
        executable: /bin/bash
      register: sops_keys
      changed_when: sops_keys.rc == 0
      failed_when: sops_keys.rc not in [0,9]

- name: Encrypt unseal keys on PKI host
  tags: keys
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/vault.yml
  vars: *vars
  pre_tasks:
    - name: Get keys from Secret
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: Secret
        name: "{{ vault_secrets['unseal'] }}"
        namespace: "{{ secret_ns }}"
      register: unseal_secret

    - name: Set unseal_keys fact
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        unseal_keys: |
          {{ unseal_secret.resources[0].data['unsealKeys'] | b64decode | from_yaml
          if unseal_secret.resources is truthy else [] }}
        root_token: |
          {{ unseal_secret.resources[0].data['rootToken'] | b64decode
          if unseal_secret.resources is truthy else '' }}
  tasks:
    - name: Create unseal-keys.asc
      when: &when
        - unseal_keys is truthy
        - unseal_keys[0] is not search('^redacted\.{3}')
      # must use pki.fourteeners.local
      # and not: pki_host (pki/cosmos)
      delegate_to: pki
      vars:
        ansible_python_interpreter: "{{ default_python_interpreter }}"
        txt_data: "{{ unseal_keys | join('\n') ~'\n' }}"
        txt_file: /opt/vault-unseal/unseal-keys.txt
        asc_file: /opt/vault-unseal/unseal-keys.asc
      block:
        - name: Write unseal-keys.txt
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin.copy_module.html
          ansible.builtin.copy:
            content: "{{ txt_data }}"
            dest: "{{ txt_file }}"
            mode: "0600"

        - name: Encrypt using OpenPGP
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
          ansible.builtin.command:
            argv:
              - gpg
              - --encrypt
              - --recipient
              # GnuPG-created user to identify encryption key
              - Vault Unseal Key <vault@{{ homelab_domain }}>
              - --armor
              - --output
              - "{{ asc_file }}"
              - --yes # overwrite
              - "{{ txt_file }}"
          changed_when: true

        # decryption could fail if YubiKey isn't ready
        # (`ykman info` and `gpg --card-status` fails)
        # or if OpenPGP card hasn't been unlocked with
        # passphrase
        - name: Decrypt unseal-keys.asc
          ansible.builtin.command:
            argv:
              - gpg
              - --decrypt
              - "{{ asc_file }}"
          register: decrypted_keys
          changed_when: false

        - name: Verify decrypted keys
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html
          ansible.builtin.assert:
            that:
              - decrypted_keys.stdout == txt_data | trim
            fail_msg: Decrypted keys do not
              match the original plain text
            quiet: true

        - name: Delete unseal-keys.txt
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
          ansible.builtin.file:
            path: "{{ txt_file }}"
            state: absent

    - name: Redact keys in Secret
      when: *when
      vars:
        secret_name: "{{ vault_secrets['unseal'] }}"
        secret_data:
          # redact all but last 3 chars of each key
          unsealKeys: "{{ unseal_keys | map('regex_replace',
            '^.+(?P<end>...)$', 'redacted...\\g<end>') | to_yaml }}"
          rootToken: "{{ root_token | regex_replace(
            '^.+(?P<end>...)$', 'redacted...\\g<end>') }}"
      ansible.builtin.include_tasks: tasks/k8s/secrets/generic.yml
