# create workspace in OpenSearch Dashboards:
# https://docs.opensearch.org/latest/dashboards/workspace/apis
# feature set enums (a.k.a. use case options):
# https://docs.opensearch.org/latest/dashboards/workspace/workspace#example-workspace-object
#
# pass the following vars:
#   ws_name     <required> workspace name
#   description [optional] workspace description
#   features    <required> workspace feature set
# requires vars from:
#   vars/opensearch.yml
#   vars/kibana.yml
# sets the following facts:
#   osd_workspace_id
---
- name: Gather facts about controller
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
  ansible.builtin.include_tasks: tasks/localfacts.yml
  when: local_python_interpreter is undefined

- name: Create Dashboards workspace
  delegate_to: localhost
  become: false
  vars:
    ansible_python_interpreter: "{{ local_python_interpreter }}"
    workspaces_url: "{{ kibana_api_url }}/workspaces"

    uri_params: &uri-params
      url_username: admin
      url_password: "{{ opensearch_admin_pass }}"
      force_basic_auth: true
      method: POST
      headers:
        osd-xsrf: "true"
      body_format: json
      return_content: true
  block:
    - name: Get existing workspaces
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
      ansible.builtin.uri:
        <<: *uri-params
        url: "{{ workspaces_url }}/_list"
        body:
          perPage: 1000
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met
      register: osd_workspaces
      retries: 5
      delay: 2

    - name: Need to create workspace?
      vars:
        existing: "{{ osd_workspaces.json.result.workspaces |
          selectattr('name', '==', ws_name) }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        existing_id: "{{ existing[0].id if existing is truthy else '' }}"

    - name: Create {{ ws_name }} workspace
      ansible.builtin.uri:
        <<: *uri-params
        url: "{{ workspaces_url }}"
        body:
          attributes:
            name: "{{ ws_name }}"
            description: "{{ description | default(omit) }}"
            features: "{{ [features] | flatten }}"
      when: existing_id is falsy
      register: osd_workspace
      changed_when: true
      retries: 5
      delay: 2

    - name: Set osd_workspace_id
      ansible.builtin.set_fact:
        osd_workspace_id: "{{ existing_id
          or osd_workspace.json.result.id }}"
