---
sudo_pass:
  cosmos: ...
  pki: ...

user_erhhung:
  username: erhhung
  firstname: ...
  lastname: ...
  fullname: ...
  email: ...
  gravatar: https://gravatar.com/avatar/...
  slack:
    handle: ...
    id: ...

homelab_admin:
  username: admin
  fullname: Homelab Admin
  email: ...
  gravatar: https://gravatar.com/avatar/...

icloud_smtp:
  # combine e-mail address
  # with actual sender name
  from_email: ...
  noreply_email: ...
  host: smtp.mail.me.com
  port: 587 # StartTLS
  username: ...
  # use app-specific passwords
  passwords:
    keycloak: ...
    awx: ...
    alerts: ...
    gitlab: ...
    jenkins: ...
    argocd: ...
    litellm: ...

slack_workspace: ...
slack_webhook_urls:
  awx: https://hooks.slack.com/services/...
  alerts: https://hooks.slack.com/services/...
  gitlab: https://hooks.slack.com/services/...
  argocd: https://hooks.slack.com/services/...
  litellm: https://hooks.slack.com/services/...

docker_access_token: ...
github_access_token: ...

age_secret_key: AGE-SECRET-KEY-...
# aes256: openssl rand -base64 32
sops_encryption_key: ...
# unlock OpenPGP on YubiKey
yubikey_unlock_pin: ...

# admin "Ansible playbooks"
pfsense_api_key: ...

# supplements vars/rancher.k3s.yml
k3s_token: ...
# supplements vars/lablabs.rke2.yml
rke2_token: ...

# MetalLB speaker memberlist secret
metallb_secret: ...

# used if bootstrap password from
# secrets no longer works because
# it has been changed from the UI
rancher_admin_pass: ...

step_ca_provisioner_pass: ...

# used for various secrets
# must be exactly 16 chars
harbor_secret: ...
# internal PostgreSQL password
harbor_db_pass: ...
# initial Harbor admin password
harbor_admin_pass: ...

# pre-defined users' passwords
# (must be between 8-40 chars)
minio_root_pass: ...
minio_admin_pass: ...
minio_client_pass: ...

# velero-repo-credentials Secret
velero_repo_pass: ...
# velero-ui-credentials Secret
velero_admin_pass: ...
# secret passphrase for issuing JWTs
velero_passphrase: ...

# initial OpenSearch admin password
opensearch_admin_pass: ...

# Kibana OpenSearch password
kibana_os_pass: ...
# Fluent OpenSearch password
fluent_os_pass: ...

# used for root & admin users
postgresql_pass: ...
pgpool_sr_pass: ...
# used for database users
pgpool_pass: ...

# temporary Keycloak admin user
keycloak_admin_pass: ...

# Keycloak OIDC client secrets
keycloak_client_secrets:
  prometheus: ...
  alertmanager: ...
  kiali: ...

# Valkey default password
valkey_pass: ...

# to encrypt sensitive
# data in the database
awx_secret_key: ...
# initial AWX admin password
awx_admin_pass: ...

# these are stored in AWX to
# run jobs with our projects
ansible_vault_pass:
  home-xcp: ...
  home-k8s: ...

# https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#generating-a-cookie-secret
# https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#cookie-options
oauth2_proxy_cookie_secret: ...

# used for scraping and more...
monitoring_pass: ...

# Thanos basic auth password
thanos_admin_pass: ...

# initial Grafana admin password
grafana_admin_pass: ...

# primary admin user's password
vault_admin_pass: ...

# initial GitLab root password
gitlab_root_pass: ...
# primary GitLab user password
gitlab_user_pass: ...

# GitLab OmniAuth configuration
gitlab_omniauth:
  # https://docs.gitlab.com/integration/github
  github:
    client_id: ...
    client_secret: ...

# primary Jenkins user password
jenkins_admin_pass: ...
# Slack bot OAuth access token
jenkins_slack_token: ...

# allowed IPs = WAN IP
buildkite_agent_token: bkct_...

# for signing JWT tokens
argocd_signing_key: ...
# initial Argo CD admin password
argocd_admin_pass: ...

# Home Assistant long-lived
# access token "prometheus"
hass_access_token: ...

# proxy key must begin with sk-
litellm_master_key: sk-...
litellm_admin_pass: ...

qdrant_api_key:
  read_write: ...
  read_only: ...

# required for cryptographic functions
searxng_secret_key: ...
# basic auth password for /metrics
searxng_metrics_pass: ...

# WEBUI_SECRET_KEY for issuing JWTs
openwebui_secret_key: ...
# initial Open WebUI admin password
openwebui_admin_pass: ...

# Open WebUI Pipelines integration
# (key is documented and expected)
openwebui_pipelines_api_key: 0p3n-w3bu!
# MCP OpenAPI proxy Bearer API key
openwebui_mcpo_api_key: ...

# de/encrypt chatflow credentials
flowise_encryption_key: ...
# must include upper+digit+symbol
#   valid symbols: (@$!%*?&-).
# invalid symbols: #
flowise_admin_pass: ...

# Anthropic "Flowise"
anthropic_api_key: sk-ant-...
# OpenAI "Default"
openai_api_key: sk-proj-...
# Groq "Flowise"
groq_api_key: gsk_...
# Serp "Default"
serp_api_key: ...

# used by MCP "weather-server"
openweather_api_key: ...

# OpenClaw shared bootstrap secret
openclaw_gateway_token: ...
openclaw_channel_secrets:
  slack:
    app_token: xapp-...
    bot_token: xoxb-...
# password used to protect keyring in
# files/openclaw/skills/gog.tar.gz.age
gogcli_keyring_pass: ...
