---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: database-priority
description: Give higher priority to database pods that are critical to the functioning of other workloads.
globalDefault: false
value: 10000
preemptionPolicy: PreemptLowerPriority
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: scanning-priority
description: Give lower priority to security scanning jobs that can be rerun when resources are available.
globalDefault: false
value: -1000
preemptionPolicy: PreemptLowerPriority
