#!/usr/bin/env bash

# CREATE CERTS USING CERT.SH SCRIPT
# (default expiration is 90  days)
# (the max expiration is 365 days)

# shellcheck disable=SC2164 # Use cd ...|| exit if cd fails

cd "$HOME"

./cert.sh --exp=365 \
          --out=admin \
  erhhung erhhung@fourteeners.local

./cert.sh --exp=365 \
  pki.fourteeners.local \
   ca.fourteeners.local

./cert.sh --exp=365 \
  firewall.fourteeners.local \
   pfsense.fourteeners.local \
    router.fourteeners.local

./cert.sh --kty=RSA \
          --exp=365 \
  pacific.fourteeners.local \
     qnap.fourteeners.local \
      nas.fourteeners.local

./cert.sh --exp=365 \
  homeassistant.fourteeners.local \
           hass.fourteeners.local \
           home.fourteeners.local \
         yellow.fourteeners.local

./cert.sh --kty=RSA \
          --exp=365 \
          --out=homeassistant_cups \
        homeassistant.fourteeners.local \
                 hass.fourteeners.local \
                 home.fourteeners.local \
  fe80::3e25:f1cb:b195:7c0a%wlan0.local \
  fe80::3e25:f1cb:b195:7c0a%wlan0 \
  localhost 192.168.0.4

./cert.sh --kty=RSA \
          --exp=365 \
  xcp \
  xcp{1..8}.fourteeners.local \
  xcp{1..8} \
  192.168.0.15{1..2} \
  192.168.0.16{1..2} \
  192.168.0.16{5..8}

./cert.sh --kty=RSA \
          --exp=365 \
   xo.fourteeners.local \
  xoa.fourteeners.local

./cert.sh --kty=RSA --p12 \
          --exp=365 \
  duplicati.fourteeners.local

./cert.sh --exp=365 \
  rancher.fourteeners.local

# rke2-ingress-nginx-controller default-ssl-certificate
./cert.sh --exp=365 \
  ingress.fourteeners.local \
    nginx.fourteeners.local \
  192.168.4.222 \
  192.168.0.17{1..8}

./cert.sh --exp=365 \
  harbor.fourteeners.local

# MinIO console
./cert.sh --exp=365 \
  minio.fourteeners.local

./cert.sh --exp=365 \
                  s3.fourteeners.local \
               \*.s3.fourteeners.local \
 \*.homelab-hl.minio.svc.cluster.local \
            \*.minio.svc.cluster.local \
            \*.minio.svc

./cert.sh --exp=365 \
  velero.fourteeners.local

./cert.sh --kty=RSA \
          --exp=365 \
          --pk8="-v1 PBE-SHA1-3DES" \
          --out=opensearch \
       opensearch-node \
       opensearch.fourteeners.local \
               es.fourteeners.local \
    \*.opensearch.svc.cluster.local \
    \*.opensearch.svc \
    192.168.4.223

./cert.sh --kty=RSA \
          --exp=365 \
          --pk8="-v1 PBE-SHA1-3DES" \
          --out=opensearch_admin \
  erhhung erhhung@gmail.com

./cert.sh --exp=365 \
  kibana.fourteeners.local

# OpenSearch client
./cert.sh --kty=RSA \
          --exp=365 \
          --pk8="-v1 PBE-SHA1-3DES" \
  fluent fluent@fourteeners.local

./cert.sh --exp=365 \
          --out=postgresql \
     postgresql-node \
     postgresql.fourteeners.local \
       postgres.fourteeners.local \
             pg.fourteeners.local \
  \*.postgresql.svc.cluster.local \
  \*.postgresql.svc \
  192.168.4.224

./cert.sh --exp=365 \
  erhhung erhhung@gmail.com

# .key file is binary
./cert.sh --exp=365 \
          --pk8="-outform DER" \
          --out=keycloak_db \
  keycloak keycloak@fourteeners.local

./cert.sh --exp=365 \
     keycloak.fourteeners.local \
          iam.fourteeners.local \
          sso.fourteeners.local \
  \*.keycloak.svc.cluster.local \
  \*.keycloak.svc

./cert.sh --exp=365 \
          --out=valkey \
        valkey-node \
        valkey.fourteeners.local \
         redis.fourteeners.local \
  valkey{1..6}.fourteeners.local \
   redis{1..6}.fourteeners.local \
     \*.valkey.svc.cluster.local \
     \*.valkey.svc \
     192.168.4.23{1..6}

./cert.sh --exp=365 \
     prometheus \
     prometheus.fourteeners.local \
        metrics.fourteeners.local \
  \*.monitoring.svc.cluster.local \
  \*.monitoring.svc \
  127.0.0.1

./cert.sh --exp=365 \
   alertmanager \
   alertmanager.fourteeners.local \
         alerts.fourteeners.local \
  \*.monitoring.svc.cluster.local \
  \*.monitoring.svc \
  127.0.0.1

# localhost used by sidecars
./cert.sh --exp=365 \
        grafana.fourteeners.local \
     monitoring.fourteeners.local \
  \*.monitoring.svc.cluster.local \
  \*.monitoring.svc \
  localhost

./cert.sh --exp=365 \
  scraper scraper@fourteeners.local

./cert.sh --exp=365 \
          --out=thanos_query \
          thanos \
          thanos.fourteeners.local \
    query.thanos.fourteeners.local \
  querier.thanos.fourteeners.local \
   \*.monitoring.svc.cluster.local \
   \*.monitoring.svc

./cert.sh --exp=365 \
          --out=thanos_rule \
         thanos \
    rule.thanos.fourteeners.local \
   ruler.thanos.fourteeners.local \
  \*.monitoring.svc.cluster.local \
  \*.monitoring.svc

./cert.sh --exp=365 \
          --out=thanos_store \
               thanos \
         store.thanos.fourteeners.local \
  storegateway.thanos.fourteeners.local \
        \*.monitoring.svc.cluster.local \
        \*.monitoring.svc

./cert.sh --exp=365 \
          --out=thanos_bucket \
            thanos \
     bucket.thanos.fourteeners.local \
  bucketweb.thanos.fourteeners.local \
     \*.monitoring.svc.cluster.local \
     \*.monitoring.svc

./cert.sh --exp=365 \
          --out=thanos_compact \
            thanos \
    compact.thanos.fourteeners.local \
  compactor.thanos.fourteeners.local \
     \*.monitoring.svc.cluster.local \
     \*.monitoring.svc

./cert.sh --exp=365 \
          --out=thanos_sidecar \
          thanos \
  sidecar.thanos.fourteeners.local \
   \*.monitoring.svc.cluster.local \
   \*.monitoring.svc

./cert.sh --exp=365 \
  kiali.fourteeners.local \
  istio.fourteeners.local

./cert.sh --exp=365 \
          --out=gitlab_db \
  gitlab gitlab@fourteeners.local

./cert.sh --exp=365 \
          --out=gitlab     gitlab-node \
                           gitlab.fourteeners.local \
                     pages.gitlab.fourteeners.local \
                  \*.pages.gitlab.fourteeners.local \
        \*.gitlab-praefect.gitlab.svc.cluster.local \
        \*.gitlab-praefect.gitlab.svc \
  \*.gitlab-gitaly-default.gitlab.svc.cluster.local \
  \*.gitlab-gitaly-default.gitlab.svc \
                        \*.gitlab.svc.cluster.local \
                        \*.gitlab.svc

./cert.sh --exp=365 \
     argocd \
     argocd.fourteeners.local \
  \*.argocd.svc.cluster.local \
  \*.argocd.svc

./cert.sh --exp=365 \
          --out=qdrant \
     qdrant-node \
     qdrant.fourteeners.local \
     qdrant-0.qdrant-headless \
     qdrant-1.qdrant-headless \
     qdrant-2.qdrant-headless \
  \*.qdrant.svc.cluster.local \
  \*.qdrant.svc

./cert.sh --exp=365 \
  ollama.fourteeners.local

./cert.sh --exp=365 \
          --out=openwebui_db \
  openwebui openwebui@fourteeners.local

./cert.sh --exp=365 \
  openwebui.fourteeners.local \
    chatgpt.fourteeners.local \
       chat.fourteeners.local

./cert.sh --exp=365 \
  flowise.fourteeners.local

./cert.sh --exp=365 \
          --out=flowise_db \
  flowise flowise@fourteeners.local

rsync certs cosmos:.
