# icloud_smtp.*:       {vault.yml}
# slack_workspace:     {vault.yml}
# jenkins_slack_token: {vault.yml}

# https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/embedded-userdatabase
jenkins_users:
  - name: Jenkins Admin
    id: ${chart-admin-username}
    password: ${chart-admin-password}
    properties:
      - mailer:
          emailAddress: "{{ homelab_admin.email }}"
      - timezone: &timezone
          timeZoneName: "{{ system_time_zone }}"

  - name: "{{ user_erhhung.fullname }}"
    id: "{{   user_erhhung.username }}"
    password: ${chart-admin-password}
    properties:
      - mailer:
          emailAddress: "{{ user_erhhung.email }}"
      - timezone: *timezone

# https://plugins.jenkins.io/
# artifactId[:version=latest]
jenkins_plugins:
  # https://plugins.jenkins.io/kubernetes
  - kubernetes
  # https://plugins.jenkins.io/git
  - git
  # https://plugins.jenkins.io/configuration-as-code
  - configuration-as-code
  # https://plugins.jenkins.io/build-user-vars-plugin
  - build-user-vars-plugin
  # https://plugins.jenkins.io/workflow-multibranch
  - workflow-multibranch
  # https://plugins.jenkins.io/workflow-aggregator
  - workflow-aggregator
  # https://plugins.jenkins.io/pipeline-lib-oras
  - pipeline-lib-oras
  # https://plugins.jenkins.io/pipeline-stage-view
  - pipeline-stage-view
  # https://plugins.jenkins.io/pipeline-graph-view
  - pipeline-graph-view
  # https://plugins.jenkins.io/markdown-formatter
  - markdown-formatter
  # https://plugins.jenkins.io/dark-theme
  - dark-theme
  # https://plugins.jenkins.io/blueocean
  - blueocean
  # https://plugins.jenkins.io/ansicolor
  - ansicolor
  # https://plugins.jenkins.io/collapsing-console-sections
  - collapsing-console-sections
  # https://plugins.jenkins.io/cloudbees-disk-usage-simple
  - cloudbees-disk-usage-simple
  # https://plugins.jenkins.io/prometheus
  - prometheus
  # https://plugins.jenkins.io/gitlab-logo
  - gitlab-logo
  # https://plugins.jenkins.io/slack
  - slack
  # https://plugins.jenkins.io/global-slack-notifier
  - global-slack-notifier
  # https://plugins.jenkins.io/embeddable-build-status
  - embeddable-build-status

# `jenkins-jenkins-config-*` ConfigMaps
# add key for each configuration area, where each corresponds
# to a plugin or section of the UI. each key is just a label,
# and can be any value to give the section a meaningful name:
# https://jenkins.fourteeners.local/configuration-as-code/reference
jenkins_jcasc_configs:
  # https://plugins.jenkins.io/dark-theme
  dark-theme: |
    appearance:
      themeManager:
        disableUserThemes: true
        # `dark` theme ignores OS settings
        theme: darkSystem # dark|darkSystem

  # https://plugins.jenkins.io/ansicolor
  ansicolor: |
    unclassified:
      ansiColorBuildWrapper:
        globalColorMapName: xterm # xterm|vga|gnome-terminal|css

  # https://plugins.jenkins.io/mailer
  mailer: |
    unclassified:
      mailer:
        smtpHost: {{ icloud_smtp.host }}
        smtpPort: {{ icloud_smtp.port }}
        useSsl: false
        useTls: true
        charset: UTF-8
        authentication:
          username: {{ icloud_smtp.username }}
          password: ${ICLOUD_PASSWORD}
        replyToAddress: {{ icloud_smtp.noreply_email }}

  # https://plugins.jenkins.io/slack
  slack: |
    unclassified:
      slackNotifier:
        teamDomain: {{ slack_workspace }}
        tokenCredentialId: slack-token
        botUser: true
        room: "#jenkins"

      # https://plugins.jenkins.io/global-slack-notifier
      globalSlackNotifier:
        notifyOnFail: true
        failureMessage: |-
          *Status*: ❌ *FAILED*
        notifyOnSuccess: true
        successMessage: |-
          *Status*: ✅ *SUCCESSFUL*
        notifyOnAborted: false
        notifyOnUnstable: true
        unstableMessage: |-
          *Status*: ⚠️ *UNSTABLE*
        notifyOnNotBuilt: false

  # https://plugins.jenkins.io/git#plugin-content-configuration-as-code
  git: |
    unclassified:
      scmGit:
        globalConfigName: {{  user_erhhung.fullname }}
        globalConfigEmail: {{ user_erhhung.email }}
        useExistingAccountWithSameEmail: true
        showEntireCommitSummaryInChanges: true

  # https://plugins.jenkins.io/build-user-vars-plugin
  build-user-vars: |
    unclassified:
      buildUserVars:
        allBuilds: true

  # https://plugins.jenkins.io/collapsing-console-sections
  collapsing-console-sections: |
    unclassified:
      collapsingSectionNote:
        sections:
          # match section format generated by Bash functions `section_start`
          # and `section_end` in the shared library (note the regex matching
          # of ANSI color codes around the title)
          - sectionStartPattern: >-
              ^.*>>>\u001B\[[\d;]+m([-:.\w]+)\u001B\[0m>>>
              \u001B\[[\d;]+m(.+?)\u001B\[0m$
            sectionEndPattern: >-
              ^.*<<<\u001B\[[\d;]+m([-:.\w]+)\u001B\[0m<<<$
            sectionDisplayName: "{2}"
            collapseSection: true

  # https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/pipeline-groovy-lib
  shared-libs: |
    unclassified:
      globalLibraries:
        libraries:
          - name: sharedlib
            # mark the library "implicit" to auto-load in
            # all pipelines without `@Library` annotation:
            # https://www.jenkins.io/doc/book/pipeline/shared-libraries#using-libraries
            implicit: true
            # not recommended because Jenkins
            # treats image tags as immutable
            defaultVersion: latest
            allowVersionOverride: true
            retriever:
              oras: # https://www.jenkins.io/doc/pipeline/steps/pipeline-groovy-lib
                containerRef: {{ harbor_container_registry }}/library/jenkins-sharedlib
                credentialsId: harbor-creds

  # https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/credentials
  credentials: |
    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  scope: GLOBAL
                  id: harbor-creds
                  description: Harbor OCI registry credentials
                  username: {{ jenkins_harbor_user }}
                  password: ${HARBOR_PASSWORD}

              - basicSSHUserPrivateKey:
                  scope: GLOBAL
                  id: github-ssh
                  description: github.com/erhhung credentials
                  username: git
                  privateKeySource:
                    directEntry:
                      privateKey: ${GITHUB_SSH_KEY}

              - string:
                  scope: GLOBAL
                  id: gitlab-token
                  description: GitLab personal access token
                  secret: ${GITLAB_TOKEN}

              - string:
                  scope: GLOBAL
                  id: slack-token
                  description: Slack bot OAuth access token
                  secret: ${SLACK_TOKEN}

  # https://plugins.jenkins.io/prometheus
  prometheus: |
    unclassified:
      prometheusConfiguration:
        collectingMetricsPeriodInSeconds: 120
        # use `prometheus` instead of `default` so that Grafana job
        # status dashboard 21628 will work without any modification
        defaultNamespace: prometheus
        collectNodeStatus: true
        collectDiskUsage: true
        perBuildMetrics: true
        perBuildMetricsMaxAgeInHours: 168 # 7 days

# `jenkins-init-scripts` ConfigMap
jenkins_init_scripts:
  # this init script is needed because the Collapsing Console Sections plugin does
  # not properly load and cache its configuration on server initialization. So, in
  # lieu of having to click Apply on the System settings page without any changes,
  # this init script loads the plugin's configuration and also populates the cache
  # https://plugins.jenkins.io/collapsing-console-sections
  collapsing-console-sections: |
    // https://github.com/jenkinsci/collapsing-console-sections-plugin/tree/master/src/main/java/org/jvnet/hudson/plugins/collapsingconsolesections/CollapsingSectionNote.java
    import org.jvnet.hudson.plugins.collapsingconsolesections.CollapsingSectionNote
    import jenkins.model.Jenkins

    def d = Jenkins.instance.getDescriptorByType(
      CollapsingSectionNote.DescriptorImpl.class)
    if (d != null) {
      d.load()
      println 'Loaded Collapsing Console Sections config'
    } else {
      println "Descriptor 'CollapsingSectionNote' not found"
    }

  # this init script is needed because the GitLab Logo plugin does not support
  # JCasC-based configuration, and we don't want manual configuration using UI
  # https://plugins.jenkins.io/gitlab-logo
  gitlab-logo: |
    // https://github.com/jenkinsci/gitlab-logo-plugin/tree/master/src/main/java/org/jenkinsci/plugins/gitlablogo/GitlabLogoProperty.java
    import org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty
    import com.cloudbees.plugins.credentials.CredentialsProvider
    import org.jenkinsci.plugins.plaincredentials.StringCredentials
    import jenkins.model.Jenkins
    import hudson.util.Secret

    def gitlabApiUrl = '{{ gitlab_service_url }}/api/v4'
    def credentialId = 'gitlab-token'

    def token = CredentialsProvider.lookupCredentials(
      StringCredentials.class, Jenkins.instance, null, null
    ).find { it.id == credentialId }?.secret?.plainText

    if (!token) {
      println "Credential '${credentialId}' not found"
      return
    }
    def d = Jenkins.instance.getDescriptorByType(
      GitlabLogoProperty.DescriptorImpl.class)
    if (d == null) {
      println "Descriptor 'GitlabLogoProperty' not found"
      return
    }
    [ 'endpointUrl':  gitlabApiUrl,
      'privateToken': Secret.fromString(token),
    ] .each { k, v ->
      def f = d.class.getDeclaredField(k)
      f.accessible = true
      f.set(d, v)
    }
    d.save()
    println 'Configured GitLab Logo plugin'
