# opensearch_admin_pass: {vault.yml}
#        kibana_os_pass: {vault.yml}

# passwords will be hashed and stored
# in opensearch_passwords_hashed fact
opensearch_passwords:
  admin: "{{ opensearch_admin_pass }}"
  erhhung: "{{ opensearch_admin_pass }}"
  kibana: "{{ kibana_os_pass }}"
  fluent: "{{ fluent_os_pass }}"
  metrics: "{{ fluent_os_pass }}"

opensearch_namespace: opensearch
opensearch_host_names: # aliases of "ingress"
  - opensearch
  - es

# remember to add opensearch.fourteeners.local and es.fourteeners.local
# to pfSense DNS as aliases of ingress.fourteeners.local: 192.168.4.222
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#products
opensearch_fqdns: "{{ opensearch_host_names | product(search_domains) | map('join','.') }}"

opensearch_cluster_name: opensearch
opensearch_master_service: "{{ opensearch_cluster_name }}-master"
opensearch_service_host: "{{ opensearch_master_service }}.{{
  opensearch_namespace }}.svc.{{ cluster_domain }}"
opensearch_service_port: 9200
opensearch_service_url: https://{{ opensearch_service_host }}:{{ opensearch_service_port }}
opensearch_url: https://{{ opensearch_fqdns | first }}:{{ opensearch_service_port }}

opensearch_secrets:
  node-tls: opensearch-node-tls # inter-node and ingress
  admin-tls: opensearch-admin-tls # run securityadmin.sh
  passwords: opensearch-passwords
  security: opensearch-security

# plugins.security in opensearch.yml
# https://docs.opensearch.org/docs/latest/install-and-configure/configuring-opensearch/security-settings
opensearch_security_plugin:
  ssl: # https://docs.opensearch.org/docs/latest/security/configuration/generate-certificates
    transport:
      # Java requires key file to be in PKCS#8 / PEM format:
      # openssl pkcs8 -topk8 -inform PEM -outform PEM -in tls.key \
      #               -v1 PBE-SHA1-3DES -nocrypt | sponge tls.key
      # paths must be relative to "<OPENSEARCH_HOME>/config"
      # "tls/" is created by extraInitContainers and mounted
      # by extraVolumeMounts
      pemcert_filepath: tls/node/tls.crt
      pemkey_filepath: tls/node/tls.key
      pemtrustedcas_filepath: tls/node/ca.crt
      enforce_hostname_verification: false
    http:
      enabled: true
      pemcert_filepath: tls/node/tls.crt
      pemkey_filepath: tls/node/tls.key
      pemtrustedcas_filepath: tls/node/ca.crt

  allow_unsafe_democertificates: false
  allow_default_init_securityindex: true
  authcz:
    admin_dn:
      - CN=erhhung,OU=Homelab,O=Fourteeners,L=Home,ST=California,C=US
  nodes_dn:
    # openssl x509 -in opensearchnode.pem -subject
    # -nameopt RFC2253 -noout | sed 's/^subject=//'
    - CN=opensearch-node,OU=Homelab,O=Fourteeners,L=Home,ST=California,C=US

  audit.type: noop
  enable_snapshot_restore_privilege: true
  check_snapshot_restore_write_privileges: true
  restapi:
    roles_enabled:
      - all_access
      - security_rest_api_access
  system_indices:
    enabled: true
    indices:
      - .opendistro-alerting-config
      - .opendistro-alerting-alert*
      - .opendistro-anomaly-results*
      - .opendistro-anomaly-detector*
      - .opendistro-anomaly-checkpoints
      - .opendistro-anomaly-detection-state
      - .opendistro-asynchronous-search-response*
      - .opendistro-notebooks
      - .opendistro-reports-*
      - .opendistro-notifications-*

# opensearch-security Secret
opensearch_security_config:
  # https://opensearch.org/docs/latest/security/configuration/yaml#internal_usersyml
  # bcrypt hash of plain-text password:
  # htpasswd -nbBC 11 "" "$ADMIN_PASS" | \
  #       tr -d ':\n' | sed 's/$2y/$2b/'
  internal_users.yml: |
    _meta:
      type: internalusers
      config_version: 2

    admin:
      description: Cluster administrator
      hash: {{ opensearch_passwords_hashed['admin'] }}
      reserved: true
      backend_roles:
        - admin

    erhhung: # YAML anchor does not work!
      description: Cluster administrator
      hash: {{ opensearch_passwords_hashed['erhhung'] }}
      reserved: false
      backend_roles:
        - admin

    kibana:
      description: Dashboards system user
      hash: {{ opensearch_passwords_hashed['kibana'] }}
      reserved: true
      backend_roles: []

    fluent:
      description: Fluent Bit/d log writer
      hash: {{ opensearch_passwords_hashed['fluent'] }}
      reserved: true
      backend_roles: []

    metrics:
      description: Prometheus metrics scraper
      hash: {{ opensearch_passwords_hashed['metrics'] }}
      reserved: true
      backend_roles: []

  # https://opensearch.org/docs/latest/security/configuration/yaml#rolesyml
  roles.yml: |
    _meta:
      type: roles
      config_version: 2

    kibana_system:
      # https://docs.opensearch.org/docs/latest/security/access-control/default-action-groups#cluster-level
      cluster_permissions:
        - cluster_monitor
      # https://docs.opensearch.org/docs/latest/security/access-control/default-action-groups#index-level
      index_permissions:
        - index_patterns:
            - "*"
          allowed_actions:
            - manage_aliases
        - index_patterns:
            - .kibana*
            - .opensearch_dashboards*
          allowed_actions:
            - manage
            - search
            - crud
      tenant_permissions:
        - tenant_patterns:
            - "*"
          allowed_actions:
            - kibana_all_write
            - opensearch_dashboards_all_write

    fluent_writer:
      cluster_permissions:
        - cluster_composite_ops
      index_permissions:
        - index_patterns:
            - fluent*
          allowed_actions:
            - create_index
            - crud

    metric_scraper:
      # https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/issues/60
      cluster_permissions:
        - cluster:monitor/prometheus/metrics
        - cluster:monitor/health
        - cluster:monitor/state
        - cluster:monitor/nodes/info
        - cluster:monitor/nodes/stats
      index_permissions:
        - index_patterns:
            - "*"
          allowed_actions:
            - indices:monitor/stats

  # https://opensearch.org/docs/latest/security/configuration/yaml#roles_mappingyml
  # https://opensearch.org/docs/latest/security/access-control/users-roles#predefined-roles
  roles_mapping.yml: |
    _meta:
      type: rolesmapping
      config_version: 2

    all_access: # predefined
      reserved: true
      hidden: false
      backend_roles:
        - admin
      hosts: []
      users:
        - admin
        - erhhung
      and_backend_roles: []

    kibana_system:
      users:
        - kibana
    fluent_writer:
      users:
        - fluent
    metric_scraper:
      users:
        - metrics

opensearch_version: "2.19.3"
# IMPORTANT! keep opensearch_version and opensearch_chart_version
# in sync: helm show chart opensearch/opensearch --version 2.xx.x
# opensearch_version will be used to select proper plugin version
# https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch
opensearch_chart_version: "2.35.0"
opensearch_release_name: opensearch

# https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch/values.yaml
opensearch_chart_values:
  replicas: 3

  clusterName: "{{ opensearch_cluster_name }}"
  masterService: "{{ opensearch_master_service }}"
  opensearchJavaOpts: -Xms256M -Xmx256M

  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "{{ opensearch_secrets['passwords'] }}"
          key: admin

  config:
    opensearch.yml: |
      cluster.name: {{ opensearch_cluster_name }}
      network.host: "0.0.0.0"
      plugins:
        # https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/security-settings
        security:
          {# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/to_nice_yaml_filter.html -#}
          {# https://tedboy.github.io/jinja2/templ14.html#indent -#}
          {{ opensearch_security_plugin | ansible.builtin.to_nice_yaml(indent=2, sort_keys=false) |
                                                                       indent(4) }}

  persistence:
    ## no need for storage level replicas when
    ## the cluster stores indices with replicas
    storageClass: "{{ storage_classes['default'] }}"
    size: 8Gi # allocate enough for logging

  extraVolumes:
    - name: node-tls
      secret:
        secretName: "{{ opensearch_secrets['node-tls'] }}"
        defaultMode: 416 # "0640"
    - name: admin-tls
      secret:
        secretName: "{{ opensearch_secrets['admin-tls'] }}"
        defaultMode: 416 # "0640"
    - name: extras
      emptyDir: {}

  extraVolumeMounts:
    - name: extras
      mountPath: /usr/share/opensearch/config/tls
      subPath: tls

  extraInitContainers:
    # https://docs.opensearch.org/docs/latest/security/configuration/index
    # https://docs.opensearch.org/docs/latest/security/configuration/generate-certificates#optional-generate-node-and-client-certificates
    - name: chmod-tls
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh"]
      args:
        - -c
        - |-
          mkdir /extras/tls
          cd    /extras/tls
          for dir in node admin; do
            mkdir     $dir
            cp   /tls/$dir/*.crt \
                 /tls/$dir/*.key $dir
            chmod 600 $dir/*.*
            chmod 700 $dir .
          done
      volumeMounts:
        - name: extras
          mountPath: /extras
        # volumes mounted in pod
        # by extraVolumes above
        - name: node-tls
          mountPath: /tls/node
          readOnly: true
        - name: admin-tls
          mountPath: /tls/admin
          readOnly: true

  rbac:
    create: true

  securityConfig: # all files in same secret
    internalUsersSecret: "{{ opensearch_secrets['security'] }}" # internal_users.yml
    rolesSecret: "{{ opensearch_secrets['security'] }}" # roles.yml
    rolesMappingSecret: "{{ opensearch_secrets['security'] }}" # roles_mapping.yml

  podAnnotations:
    # since the Helm template does not include security config checksum
    # when specifying individual secrets like we do above as opposed to
    # providing securityConfig.config.data to replace all config files,
    # we manually add that same annotation so that StatefulSet pods get
    # restarted when security config is updated
    securityconfigchecksum: |-
      {# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hash_filter.html -#}
      {% set hash = opensearch_security_config |
                       ansible.builtin.to_yaml |
                       ansible.builtin.hash('sha256') -%}
      {{ hash[:63] }}

  resources:
    requests:
      cpu: 200m
      memory: 1Gi

  priorityClassName: "{{ priority_classes['database'] }}"

  # avoid CPU surge in weak cluster
  podManagementPolicy: OrderedReady

  readinessProbe: &probe
    tcpSocket:
      port: "{{ opensearch_service_port }}"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  livenessProbe: *probe
  startupProbe: {}

  service:
    labelsHeadless:
      # add labels to the regular service to differentiate it from the headless service
      # so that the ServiceMonitor selector can target just one service instead of both;
      # however, the chart currently offers no way to add extra ServiceMonitor selector
      # labels: https://github.com/opensearch-project/helm-charts/issues/673
      prometheus.io/scrape: "true"

  ingress:
    enabled: true
    tls:
      - secretName: "{{ opensearch_secrets['node-tls'] }}"
        hosts: "{{ opensearch_fqdns }}"
    ingressClassName: "{{ rke_ingress_class }}"
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    hosts: "{{ opensearch_fqdns }}"

  plugins:
    enabled: true
    # https://docs.opensearch.org/docs/latest/install-and-configure/plugins#available-plugins
    # additional: https://github.com/opensearch-project/OpenSearch/tree/main/plugins
    # https://docs.opensearch.org/docs/latest/install-and-configure/plugins
    installList:
      # - telemetry-otel
      # - repository-s3
      # - https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/releases/download/{{
      #   opensearch_version }}.0/prometheus-exporter-{{ opensearch_version }}.0.zip

      # since the "official" GitHub repo hasn't released new plugin versions
      # to match newer OpenSearch versions, including the version we install,
      # I've recompiled the 2.17.1.0 source code as 2.19.3.0 and released it
      # in my forked repo
      - https://github.com/erhhung/prometheus-exporter-plugin-for-opensearch/releases/download/{{
        opensearch_version }}.0/prometheus-exporter-{{ opensearch_version }}.0.zip

  extraObjects:
    # create LoadBalancer service to listen on port 9200
    # in addition to the ingress controller on port 443
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{ opensearch_master_service }}-external"
        labels:
          app.kubernetes.io/name: opensearch
          app.kubernetes.io/instance: "{{ opensearch_cluster_name }}"
          app.kubernetes.io/component: "{{ opensearch_master_service }}"
        annotations:
          # replaces deprecated .spec.loadBalancerIP field
          metallb.universe.tf/loadBalancerIPs: "{{ metallb_vips['opensearch'] }}"
      spec:
        type: LoadBalancer
        ports:
          - name: http
            port: "{{ opensearch_service_port }}"
            protocol: TCP
            targetPort: http
            appProtocol: https
        selector:
          app.kubernetes.io/name: opensearch
          app.kubernetes.io/instance: "{{ opensearch_cluster_name }}"

  # this will only create the ServiceMonitor resource,
  # but metrics won't be available for scraping unless
  # the prometheus-exporter plugin has been installed!
  serviceMonitor:
    enabled: "{{ prometheus_crds_installed }}"
    labels:
      release: "{{ monitoring_release_name }}"
    # https://github.com/opensearch-project/helm-charts/pull/674
    selectorLabels:
      prometheus.io/scrape: "true"
    path: /_prometheus/metrics
    scheme: https
    # monitoring-scraper-tls Secret must be recreated in the
    # OpenSearch namespace where this ServiceMonitor resides
    tlsConfig: "{{ metric_scraper_tls_config }}"
    basicAuth:
      enabled: true
      # credentials Secret is expected by the chart
      # template to contain "username" & "password"
      existingSecret: opensearch-creds-metrics

# https://grafana.com/grafana/dashboards/?search=OpenSearch&dataSource=prometheus
opensearch_grafana_dashboards:
  # https://grafana.com/grafana/dashboards/23029-opensearch
  - title: OpenSearch
    gnet_id: 23029
    tags:
      - opensearch
      - logging
