# explicitly allow tools in sessions because
# `group:openclaw` doesn't appear to include
# `exec`/`process`:
# https://docs.openclaw.ai/tools#built-in-tools
openclaw_allow_tools:
  - exec
  - process
  - browser
  - canvas
  # - nodes
  # plugins:
  - lcm_grep
  - lcm_describe
  - lcm_expand
  - lcm_expand_query
  - searxng_search

# allowlist: ~/.openclaw/exec-approvals.json
# applies to all agents (agents.*.allowlist)
# see `tools.exec.{security,ask}` settings:
# https://docs.openclaw.ai/tools/exec
openclaw_exec_allowlist:
  common:
    # glob pattern that doesn't contain /
    # will be resolved using `command -v`
    - ls
    - cat
    - sed
    - awk
    - grep
    - find
    - head
    - tail
    - sort
    - date
    - uname
    - jq
    - yq
    - rg
  gateway:
    - gog
  # allowlist on the Mac node is
  # provisioned manually for now
  node: []

# will be converted into JSON and stored as
# openclaw.json in the "openclaw" ConfigMap:
# https://docs.openclaw.ai/gateway/configuration
# show config in YAML: yq -pj openclaw.json -Moy
openclaw_config:
  # https://docs.openclaw.ai/gateway/configuration-reference#gateway
  gateway:
    port: 18789
    bind: lan # loopback|lan
    mode: local # local|remote
    auth:
      mode: token # none|token|password|trusted-proxy
      token: ${OPENCLAW_GATEWAY_TOKEN}
      rateLimit:
        maxAttempts: 10
        windowMs: 60000
        lockoutMs: 300000

    # https://docs.openclaw.ai/web/control-ui
    controlUi:
      enabled: true
      # prepend: filter_plugins/filters.py
      allowedOrigins: "{{ openclaw_fqdns | map('prepend', 'https://') }}"

    # NOTE: CIDR notation isn't supported:
    # https://github.com/openclaw/openclaw/pull/8752
    trustedProxies: "{{ [cluster_cidr] }}"

    # https://docs.openclaw.ai/nodes
    nodes:
      # run `openclaw nodes status --json` to see
      # commands that each node actually supports.
      # allowing commands like system.run.prepare
      # will not magically grant new capabilities
      # if the node doesn't implement the command.
      # https://docs.openclaw.ai/platforms/macos#node-capabilities-mac
      allowCommands:
        - invoke
        - system.which
        - system.notify

        # in-app UI surface controls
        # via Apple native WKWebView
        - canvas.present
        - canvas.navigate
        - canvas.snapshot
        - canvas.hide

        # higher risk: run arbitrary JS
        # in node-hosted canvas/webview
        # - canvas.eval

        # canvas streaming controls
        # https://a2ui.org/
        - canvas.a2ui.push
        - canvas.a2ui.pushJSONL
        - canvas.a2ui.reset

        # higher risk: browser access
        # with pre-signed-in sessions
        # https://docs.openclaw.ai/tools/browser#node-browser-proxy-zero-config-default
        - browser.proxy

        # higher risk: location access
        # https://docs.openclaw.ai/nodes/location-command
        # - location.get

        # higher risk: capture screen
        - screen.capture
        # - screen.record
        - screen.snap

        # higher risk: camera access
        # https://docs.openclaw.ai/nodes/camera#commands-via-gateway-node-invoke
        # - camera.list
        # - camera.snap
        # - camera.clip

        # higher risk: arbitrary remote
        # command execution on the node
        - system.run
        - system.run.prepare

  # https://docs.openclaw.ai/gateway/configuration-reference#browser
  browser:
    enabled: true
    ssrfPolicy:
      # allow browsing local network sites
      dangerouslyAllowPrivateNetwork: true
    # allow arbitrary JavaScript execution in the page context:
    # https://docs.openclaw.ai/tools/browser#security-&-privacy
    evaluateEnabled: false

    defaultProfile: default
    profiles:
      default: # Chromium sidecar
        cdpUrl: http://localhost:9222
        color: "#4285F4"

  # https://docs.openclaw.ai/concepts/multi-agent
  agents:
    # https://docs.openclaw.ai/gateway/configuration-reference#agent-defaults
    defaults:
      workspace: ${OPENCLAW_HOME}/workspace
      userTimezone: ${TZ}
      timeFormat: "12" # auto|12|24

      # https://docs.openclaw.ai/gateway/configuration-reference#agents-defaults-model
      model:
        # prefer ChatGPT subscription
        primary: openai-codex/gpt-5.4
        fallbacks:
          - litellm/gpt-5.4
          - litellm/gpt-5.2
          - litellm/claude-sonnet-4-5
          - litellm/claude-sonnet-4-6
      maxConcurrent: 1
      timeoutSeconds: 600

      # default thinking budget level when no `/think` directive
      thinkingDefault: low # "off"|minimal|low|medium|high|xhigh|adaptive
      # default tool/output verbosity when no `/verbose` directive
      verboseDefault: "off" # "off"|"on"|full
      # default elevated-execution mode when no `/elevated` directive
      elevatedDefault: full # "off"|"on"|ask|full

      # https://docs.openclaw.ai/gateway/configuration-reference#agents-defaults-sandbox
      # run `openclaw sandbox explain` on gateway
      # to see effective sandbox and tool policy;
      # also `tools.sandbox.tools.alsoAllow|deny`
      sandbox:
        # https://docs.openclaw.ai/gateway/sandboxing#modes
        mode: "off" # "off"|non-main|all
        # use the same path as `agents.defaults.workspace`
        workspaceRoot: ${OPENCLAW_HOME}/workspace
        # https://docs.openclaw.ai/gateway/sandboxing#workspace-access
        workspaceAccess: rw # none|ro|rw

    # single "main" agent by default, but can create separate agents like "home"
    # and "work", each with independent workspaces, policies, skills, and memory
    # https://docs.openclaw.ai/gateway/configuration-reference#agents-list-per-agent-overrides
    list:
      # https://docs.openclaw.ai/concepts/multi-agent#single-agent-mode-default
      - id: main
        default: true
        identity:
          name: OpenClaw
          emoji: 🦞
        tools:
          alsoAllow: "{{ openclaw_allow_tools }}"

  # channel setup is not required--the
  # Control UI is suitable chat client
  # https://docs.openclaw.ai/gateway/configuration-reference#channels
  channels:
    # https://docs.openclaw.ai/channels/slack
    # https://docs.openclaw.ai/gateway/configuration-reference#slack
    # https://api.slack.com/apps/A0ANTQVU18C/general
    slack:
      enabled: true
      mode: socket # socket|http
      appToken: ${SLACK_APP_TOKEN}
      botToken: ${SLACK_BOT_TOKEN}
      capabilities:
        # allow agent to generate Slack-specific
        # UI controls like buttons and dropdowns:
        # https://docs.openclaw.ai/channels/slack#interactive-replies
        interactiveReplies: true

      dm:
        enabled: true
        groupEnabled: false
      dmPolicy: allowlist # pairing|allowlist|open|disabled
      # allow list must use Slack stable IDs (U*), not user
      # handles (get the ID by clicking on a user's profile
      # and then selecting ⋮ (More) -> Copy member ID)
      allowFrom: &slack-allow-from
        - "{{ user_erhhung.slack.id }}"
      channels:
        # get stable ID from a channel's details -> About
        # NOTE: bot token scopes must include groups:read
        # to access private channel metadata
        C0ANU3H557Y: # #assistant (private)
          enabled: true
          requireMention: true

      allowBots: false # prevents reply loops
      # reply into threads? `first` will reuse a single thread
      # per channel; `all` will create a thread per triggering
      # message in a channel; `off` to not use threads at all
      replyToMode: "off" # "off"|first|all
      # how many recent channel/group messages
      # to include in the agent's chat context
      historyLimit: 10

  # https://docs.openclaw.ai/gateway/configuration-reference#session
  session:
    scope: per-sender
    dmScope: per-peer # main|per-peer|per-channel-peer|per-account-channel-peer
    store: ${OPENCLAW_HOME}/sessions
    # resetting session limits
    # the agent's chat context
    reset:
      mode: idle
      idleMinutes: 240

  # https://docs.openclaw.ai/gateway/configuration-reference#logging
  logging:
    # `level` is for file-based logging;
    # `consoleLevel` is container stdout:
    # https://docs.openclaw.ai/logging
    level: trace # error|warn|info|debug|trace
    file: /tmp/openclaw.log # JSONL format
    consoleLevel: trace
    consoleStyle: pretty # pretty|compact|json
    redactSensitive: "off" # "off"|tools

  # https://docs.openclaw.ai/logging#export-to-opentelemetry
  diagnostics:
    enabled: true
    otel:
      enabled: true
      endpoint: https://{{ otlp_http_endpoint }}
      protocol: http/protobuf # no gRPC support
      serviceName: openclaw-gateway
      traces: true
      metrics: true
      logs: false
      sampleRate: 1
      flushIntervalMs: 30000

  # https://docs.openclaw.ai/gateway/configuration-reference#auth-storage
  auth:
    profiles:
      # https://docs.openclaw.ai/providers/openai#option-b-openai-code-codex-subscription
      # see credentials file: files/openclaw/state/agents/main/agent/auth-providers.json
      openai-codex:erhhung:
        provider: openai-codex
        mode: oauth

  # https://docs.openclaw.ai/gateway/local-models#other-openai-compatible-local-proxies
  models:
    providers:
      # https://docs.openclaw.ai/providers/ollama
      ollama:
        baseUrl: "{{ ollama_service_url }}"
        # no auth currently enforced
        # apiKey: ${OLLAMA_API_KEY}
        api: ollama
        # see `ollama_models`
        # in vars/ollama.*.yml
        models:
          # https://ollama.com/library/gemma3
          - id: gemma3:4b
            name: Gemma 3:4b ⟺ Ollama

      # https://docs.openclaw.ai/providers/litellm
      # https://docs.litellm.ai/docs/tutorials/openclaw_integration#config-reference
      litellm:
        baseUrl: "{{ litellm_service_url }}"
        apiKey: ${LITELLM_API_KEY}
        api: openai-completions
        # see `litellm_models`
        # in vars/litellm.yml
        models:
          # https://platform.openai.com/docs/models
          - id: gpt-5.2
            name: GPT-5.2 ⟺ LiteLLM
          - id: gpt-5.4
            name: GPT-5.4 ⟺ LiteLLM
          # https://www.anthropic.com/claude/sonnet
          - id: claude-sonnet-4-5
            name: Claude Sonnet 4.5 ⟺ LiteLLM
          - id: claude-sonnet-4-6
            name: Claude Sonnet 4.6 ⟺ LiteLLM

  # https://docs.openclaw.ai/gateway/configuration-reference#tools
  tools:
    profile: full # minimal|coding|messaging|full

    # allow all built-in tools plus additional plugin tools
    allow: "{{ ['group:openclaw'] + openclaw_allow_tools }}"
    deny: []

    # https://docs.openclaw.ai/gateway/sandbox-vs-tool-policy-vs-elevated
    # run `openclaw sandbox explain` on gateway
    # to see effective sandbox and tool policy
    sandbox:
      tools:
        # enable tools denied by
        # default sandbox policy
        alsoAllow: "{{ openclaw_allow_tools }}"

    # https://docs.openclaw.ai/tools/elevated
    elevated:
      allowFrom:
        webchat:
          - openclaw-control-ui
        slack: *slack-allow-from

    # https://docs.openclaw.ai/tools/exec
    # exec host=node routing is currently broken:
    # https://github.com/openclaw/openclaw/issues/59533
    # https://github.com/openclaw/openclaw/issues/20669
    exec:
      host: auto # auto|sandbox|gateway|node
      # custom node ID is supposed to be set by `openclaw node run --node-id`
      # arg in files/openclaw/mac/ai.openclaw.macos.sh, but it's not working:
      # https://github.com/openclaw/openclaw/issues/61569
      node: Erhhung's i9 MBP # erhhungs-i9-mbp
      security: allowlist # deny|allowlist|full
      ask: on-miss # "off"|on-miss|always

    web:
      # https://docs.openclaw.ai/tools/web-fetch
      fetch:
        enabled: true
        maxChars: 50000 # default max output chars
        maxCharsCap: 50000 # hard cap for maxChars param
        maxResponseBytes: 2000000 # max size before truncation
        maxRedirects: 3
        timeoutSeconds: 30
        cacheTtlMinutes: 15
        readability: true
        userAgent: >-
          Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
          AppleWebKit/537.36 (KHTML, like Gecko)
          Chrome/146.0.0.0 Safari/537.36

      # https://docs.openclaw.ai/tools/web
      search:
        # use `searxng_search` tool instead
        enabled: false
        # see perplexity plugin config for LiteLLM
        # search API setup (currently not working):
        # https://github.com/openclaw/openclaw/issues/53586
        provider: perplexity
        maxResults: 10
        timeoutSeconds: 30
        cacheTtlMinutes: 15

  # https://docs.openclaw.ai/tools/plugin
  # list plugins: `openclaw plugins list`
  plugins:
    # only allow listed plugins, whether bundled or
    # custom, to load (each must still be enabled):
    allow: |
      {{ openclaw_plugins | map(attribute='id') + [
           'slack',
           'browser',
           'diagnostics-otel',
           'openai',
           'litellm',
           'perplexity',
           'memory-core',
         ] }}

    # declare plugins ALREADY installed by init container
    # or else OpenClaw annoyingly outputs "loaded without
    # install/load-path provenance" warnings:
    # https://github.com/openclaw/openclaw/issues/43655
    # `plugin_integrity` is fact set by task
    installs: |
      {% set installs = {} %}
      {% for plugin in openclaw_plugins %}
      {%   set _ = installs.update({
             plugin.id: {
               'source':      'npm',
               'spec':         plugin.package ~'@'~ plugin.version,
               'version':      plugin.version,
               'installPath': '${OPENCLAW_PLUGIN_DIR}/' ~ plugin.id,
             } | combine(plugin_integrity[plugin.id]),
           })     %}
      {% endfor   %}
      {{ installs }}

    load:
      # prepend: filter_plugins/filters.py
      paths: "{{ openclaw_plugins | map(attribute='id') |
        map('prepend', '${OPENCLAW_PLUGIN_DIR}/') }}"

    # https://docs.openclaw.ai/tools/plugin#plugin-slots-exclusive-categories
    slots:
      contextEngine: lossless-claw

    entries:
      slack:
        enabled: true
      browser:
        enabled: true
      openai:
        enabled: true
      litellm:
        enabled: true
      diagnostics-otel:
        enabled: true

      # https://github.com/Martian-Engineering/lossless-claw#configuration
      lossless-claw:
        enabled: true
        config:
          ignoreSessionPatterns:
            - agent:*:cron:**

      # https://github.com/erhhung/openclaw-searxng-search#configuration
      searxng-search:
        enabled: true
        config:
          baseUrl: "{{ searxng_service_url }}"
          defaultCount: 10
          timeoutMs: 30000

      # use LiteLLM's Perplexity-compatible API to proxy
      # search queries to backing providers like SearXNG:
      # https://docs.openclaw.ai/tools/perplexity-search
      perplexity:
        enabled: true
        config:
          webSearch:
            apiKey: ${LITELLM_API_KEY}
            baseUrl: "{{ litellm_service_url }}/search/{{
              litellm_search_tools[0].search_tool_name }}"

  # https://docs.openclaw.ai/tools/skills#config-overrides-/-openclaw/openclaw-json
  skills:
    entries:
      # https://clawhub.ai/conorkenn/openclaw-github-assistant
      openclaw-github-assistant:
        config:
          github:
            username: erhhung
            token: ${GITHUB_ACCESS_TOKEN}
