# install packages not included by default
# in the Ubuntu 24.04 minimal installation

# see installed packages:
# apt list --installed

# see tasks/packages/apt/sources.yml
# for item specs and default values
apt_sources:
  # https://helm.sh/docs/intro/install#from-apt-debianubuntu
  - keyring:
      file: helm-archive-keyring.gpg
      url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    sources:
      file: helm.sources
      uris: https://packages.buildkite.com/helm-linux/helm-debian/any
      suites: any

  # https://developer.hashicorp.com/vault/install#linux
  - keyring:
      file: hashicorp-archive-keyring.gpg
      url: https://apt.releases.hashicorp.com/gpg
    sources:
      file: hashicorp.sources
      uris: https://apt.releases.hashicorp.com

apt_repositories:
  - repos:
      # https://dgpu-docs.intel.com/driver/client/overview.html
      - ppa:kobuk-team/intel-graphics
    # GPU passthrough enabled hosts
    hosts: &gpu-hosts
      - k8s3
      - k8s4
      - k8s5
      - k8s6

apt_packages:
  - packages:
      - linux-modules-extra-{{ ansible_kernel }} # GPU drivers
      - apt-transport-https
      - locales # required by community.general.locale_gen
      - bash-completion # required by crictl/kubectl completion
      - less
      - tree
      - htop
      - iotop
      - lsof # used by custom Bash function `listening`
      - rsync # required by ansible.posix.synchronize
      - unzip
      - emacs-nox # yours truly's editor by muscle memory
      # iptables is required by Canal/Calico CNI in RKE2:
      # https://github.com/rancher/rke2/issues/4385#issuecomment-1738848974
      - iptables
      #- nftables
      #- ipset
      - dnsutils # provides nslookup/dig/host
      - iputils-ping
      - netcat-openbsd
      - parted # used manually to expand local storage
      - open-iscsi # required by Longhorn storage engine
      - nfs-common # required by Longhorn storage engine
      - python3-pip
      - python3-virtualenv # required by ansible.builtin.pip
      # yq from Apt is not the mikefarah/yq package we want
      - jq
      - jo
      - git # required by kubernetes.core.helm_plugin
      - helm # requires /etc/apt/sources.list.d/helm.sources
      - skopeo # used to copy container images into Harbor
    hosts: "{{ groups['k8s_all'] }}"

  - packages:
      # useful tools to debug MetalLB routing issues
      - tcpdump
      - tshark
      #- conntrack
    hosts: "{{ groups['cluster'] }}"

  # PPA packages below offer support for Intel client GPUs:
  # https://dgpu-docs.intel.com/driver/client/overview.html
  - packages:
      - libze-intel-gpu1
      - libze1
      - intel-gsc
      - intel-metrics-discovery
      - intel-opencl-icd
      - clinfo
      - intel-media-va-driver-non-free
      - libmfx-gen1
      - libvpl2
      - libvpl-tools
      - libva-glx2
      - va-driver-all
      - vainfo
    # GPU passthrough enabled hosts
    hosts: *gpu-hosts

# packages will be installed under
# virtualenv ansible_user_dir/.venv
pip_packages:
  - PyYAML
  - jsonpatch
  - kubernetes # required by kubernetes.core.k8s
  - kubernetes-validate

# {name, path, state} all fields optional:
# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_plugin_module.html
helm_plugins:
  - path: https://github.com/databus23/helm-diff
  - path: https://github.com/aslafy-z/helm-git
