# these tasks are included by "Apply updated security config"
# handler, which, apparently, cannot have a block of subtasks
---
# security config change would trigger
# a rolling update of StatefulSet pods
- name: Wait for OpenSearch to be ready
  vars:
    res_kind: StatefulSet
    res_name: "{{ opensearch_master_service }}"
    res_ns: "{{ opensearch_namespace }}"
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
  ansible.builtin.include_tasks: tasks/k8s/waitready.yml

# https://docs.opensearch.org/docs/latest/security/configuration/security-admin/
# it is sufficient to run securityadmin.sh on a single pod
# because the config is stored in the .opendistro_security
# index, which gets replicated to all other nodes
- name: Run OpenSearch securityadmin.sh
  vars:
    home_dir: /usr/share/opensearch
    plugin_dir: "{{ home_dir }}/plugins/opensearch-security"
    config_dir: "{{ home_dir }}/config"
    tls_dir: "{{ config_dir }}/tls/admin"
    # "/tls/" is created by extraInitContainers and mounted
    # by extraVolumeMounts
    command: >-
      {{ plugin_dir }}/tools/securityadmin.sh
      -cd  {{ config_dir }}/opensearch-security
      -cert   {{ tls_dir }}/tls.crt
      -key    {{ tls_dir }}/tls.key
      -cacert {{ tls_dir }}/ca.crt
      --disable-host-name-verification
      --ignore-clustername
      --accept-red-cluster
  # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_exec_module.html
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ opensearch_namespace }}"
    pod: "{{ opensearch_master_service }}-0"
    container: opensearch
    command: "{{ command }}"
  timeout: 300
