# restart `systemd-resolved` service on host
# if DNS isn't working, i.e., cannot resolve
# the test domain to its expected IP
#
# pass the following vars:
#   test_domain [optional] default=pki.fourteeners.local
#   expected_ip [optional] default=192.168.0.5
---
- name: Ensure DNS resolution is working
  become: true
  block:
    - name: Is {{ homelab_domain }} DNS working?
      vars:
        _test_domain: "{{ test_domain | default('pki.'~ homelab_domain) }}."
        _expected_ip: "{{ expected_ip | default(hostvars['pki'].ansible_host) }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        set -o pipefail

        # ignore SIGPIPE (rc=141) with pipefail:
        # https://www.pixelbeat.org/programming/sigpipe_handling.html
        { dig +short {{ _test_domain }} || true; } | grep -q {{ _expected_ip }}
      args:
        executable: /bin/bash
      register: is_dns_working
      changed_when: false
      failed_when: false

    - name: Restart systemd-resolved service
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: restarted
      when: is_dns_working.rc != 0
