# pass the following vars:
#   vcluster <required> object {name,node}
#   webhooks [optional] MutatingWebhookConfiguration.webhooks[]
---
- name: Create vCluster "{{ vcluster.name }}"
  become: false
  vars:
    vcluster_ns: vcluster-{{ vcluster.name }}
  block:
    - name: Create vCluster persistent volumes
      vars:
        pv_list:
          # - name: "{{ vcluster_ns }}-etcd-pv"
          #   role: etcd # controlPlane.backingStore.etcd.deploy.statefulSet.persistence
          #   size: "{{ vcluster_pv_sizes['etcd'] }}"
          - name: "{{ vcluster_ns }}-data-pv"
            role: data # controlPlane.statefulSet.persistence
            size: "{{ vcluster_pv_sizes['data'] }}"
      block:
        - name: Create node-local file system path
          delegate_to: "{{ vcluster.node }}"
          become: true
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
          ansible.builtin.file:
            path: "{{ data_lv.mount ~'/'~ item.name }}"
            state: directory
            mode: "0755"
          loop: "{{ pv_list }}"
          loop_control:
            label: "{{ vcluster.node ~'|'~ item.name }}"

        - name: Create vCluster persistent volume
          # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig }}"
            # https://kubernetes.io/docs/concepts/storage/volumes#local
            definition:
              apiVersion: v1
              kind: PersistentVolume
              metadata:
                name: "{{ item.name }}"
                labels:
                  app: vcluster
                  release: "{{ vcluster.name }}"
                  node: "{{    vcluster.node }}"
                  role: "{{        item.role }}"
              spec:
                storageClassName: "{{ storage_classes['local'] }}"
                capacity:
                  storage: "{{ item.size }}"
                local:
                  path: "{{ data_lv.mount }}/{{ item.name }}"
                accessModes: ["ReadWriteOnce"]
                volumeMode: Filesystem
                nodeAffinity:
                  required:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: kubernetes.io/hostname
                            operator: In
                            values: "{{ [vcluster.node] }}"
                persistentVolumeReclaimPolicy: Retain
            validate:
              fail_on_error: true
            state: present
            apply: true
            wait: true
          loop: "{{ pv_list }}"
          loop_control:
            label: "{{ item.name ~'|'~ item.size }}"

    # https://www.vcluster.com/docs/platform/use-platform/virtual-clusters/add-virtual-clusters
    - name: Create externally managed vCluster
      block:
        - name: Create VirtualClusterInstance resource
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig }}"
            # https://www.vcluster.com/docs/platform/api/resources/virtualclusterinstance
            definition:
              apiVersion: management.loft.sh/v1
              kind: VirtualClusterInstance
              metadata:
                name: "{{ vcluster.name }}"
                namespace: "{{ vcluster_project_namespace }}"
              spec:
                displayName: vCluster "{{ vcluster.name }}"
                networkPeer: true
                external: true
                template:
                  helmRelease:
                    chart:
                      version: "{{ vcluster_chart_version }}"
            state: present
            apply: true
            wait: true

        - name: Get VirtualClusterAccessKey subresource
          # use kubectl because k8s_info does
          # not support fetching subresources
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
          ansible.builtin.shell: |
            # run Bash and source /etc/profile.d
            # scripts so that kubectl is in PATH
            exec /bin/bash -l <<'EOT'

            kubectl get -n {{ vcluster_project_namespace }} \
              virtualclusterinstance.management.loft.sh {{ vcluster.name }} \
              --subresource accesskey -o json
            EOT
          register: vc_access_key
          changed_when: false

        # create Secret referenced by tenant config `platform.apiKey.secretName`
        # https://www.vcluster.com/docs/platform/install/air-gapped#deploy-vcluster-using-helm
        # https://github.com/loft-sh/vcluster/tree/main/pkg/platform/secret.go#L93
        - name: Create vCluster Platform API key secret
          vars:
            access_key: "{{ (vc_access_key.stdout | from_json).accessKey }}"

            # === Inputs ===
            secret_ns: "{{ vcluster_ns }}"
            secret_name: "{{ vcluster_platform_secrets['api-key'] }}"
            secret_data:
              accessKey: "{{ access_key }}"
              host: "{{ vcluster_platform_fqdn }}"
              certificateAuthorityData: "{{ ca_certificates[1] }}"
              insecure: "false"
              project: default
              # `name` is required, or else the vCluster syncer will fail with "error
              # registering vCluster: seems like virtual cluster instance got deleted"
              name: "{{ vcluster.name }}"
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
          ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/generic.yml"

    - name: Install vCluster tenant Helm chart
      vars:
        # var referenced in templates/vcluster/tenant.yaml.j2
        vcluster_fqdn: "{{ vcluster_domains[vcluster.name] }}"
      block:
        - name: Install vCluster tenant Helm chart
          vars:
            # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_lookup.html
            values_: "{{ lookup('ansible.builtin.template', templates_dir ~ '/vcluster/tenant.yaml.j2') }}"

            # === Inputs ===
            tmpdir_name: vcluster-{{ vcluster.name }}
            repo_name: vcluster
            repo_url: https://charts.loft.sh
            chart_ref: vcluster
            chart_ver: "{{ vcluster_chart_version }}"
            release: "{{ vcluster.name }}"
            release_ns: "{{ vcluster_ns }}"
            values: "{{ values_ | from_yaml }}"

            patches:
              # vCluster Helm chart creates a config Secret with "config.yaml"
              # key and value {{ .Values | toYaml }}, but since we adopt extra
              # resources using bedag/raw subchart, .exxtraas gets included in
              # the config.yaml, which the controller cannot unmarshal, so use
              # a post-renderer to remove .exxtraas from the Secret
              post_renderers:
                - |
                  #!/usr/bin/env bash
                  set -euo pipefail

                  echo >&2 "$0"
                  yaml="$(cat)"

                  # https://github.com/loft-sh/vcluster/tree/main/chart/templates/config-secret.yaml
                  export NAME="vc-config-{{ vcluster.name }}"

                  config="$(yq 'select(
                    .kind == "Secret" and .metadata.name == env(NAME)
                    ) | .data."config.yaml" // "" | @base64d' <<< "$yaml")"

                  if [ "$config" ]; then
                    # delete subchart values that
                    # aren't spec for config.yaml
                    CONFIG="$(yq 'del(.exxtraas)' <<< "$config")" \
                      yq 'with(select(
                        .kind == "Secret" and .metadata.name == env(NAME)
                        ); .data."config.yaml" = (strenv(CONFIG) | @base64)
                        )' <<< "$yaml"
                  else
                    echo "$yaml"
                  fi
            extras: # adopt extra resources into Helm release
              - v1 Secret {{ vcluster_platform_secrets['api-key'] }}
          ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/helmfile.yml"

        - name: Fetch vCluster kubeconfig
          # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html
          kubernetes.core.k8s_info:
            kubeconfig: "{{ kubeconfig }}"
            api_version: v1
            kind: Secret
            name: vc-{{ vcluster.name }}
            namespace: "{{ vcluster_ns }}"
          register: vc_secret
          until: vc_secret.resources is truthy
          retries: 12
          delay: 5

        - name: Merge into local kubeconfig
          vars:
            # b64_decode_k8s_secret: plugins/filter/filters.py
            kubeconfig_in: "{{ (vc_secret.resources[0] | b64_decode_k8s_secret).config }}"
            context: x{{ vcluster.name }}
            server: https://{{ vcluster_fqdn }}
          ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/kubeconfig.yml"
      rescue:
        - name: Delete vCluster resources
          ansible.builtin.include_tasks: "{{ tasks_dir }}/vcluster/delete.yml"

        - name: Terminate play on failure
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fail_module.html
          ansible.builtin.fail:
            msg: Failed to create vCluster "{{ vcluster.name }}"!
