# create kubeconfig data containing one or
# more vClusters using their internal URLs
#
# pass the following vars:
#   vcluster_names  [optional] default=<all>
#   current_context [optional] default=<first>
# sets the following facts:
#   vcluster_kubeconfig  kubeconfig data dict
---
- name: Gather facts about controller
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
  ansible.builtin.include_tasks: "{{ tasks_dir }}/localfacts.yml"
  when: local_python_interpreter is undefined

- name: Include vars/vclusters.yml
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_vars_module.html
  ansible.builtin.include_vars: "{{ vars_dir }}/vclusters.yml"
  when: vclusters is undefined

- name: Create vCluster kubeconfig
  vars:
    vc_names: "{{ vcluster_names | default(vclusters | map(attribute='name')) }}"
    temp_file: /tmp/kubeconfig-vclusters
  block:
    - name: Get vCluster kubeconfig data
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html
      kubernetes.core.k8s_info:
        kubeconfig: "{{ rke_kubeconfig }}"
        api_version: v1
        kind: Secret
        name: vc-{{ item }}
        namespace: vcluster-{{ item }}
      loop: "{{ vc_names }}"
      register: vc_kubeconfigs

    - name: Create temp kubeconfig file
      delegate_to: localhost
      vars:
        ansible_python_interpreter: "{{ local_python_interpreter }}"
        configs: |
          {{  vc_kubeconfigs.results | map(attribute='resources') | map('first')
                                     | map(attribute='data.config')
                                     | map('b64decode') | map('from_yaml') }}
        context: "{{ current_context | default(vc_names | first) }}"
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/kubeconfig_module.html
      kubernetes.core.kubeconfig:
        path: "{{ temp_file }}"
        clusters: |
          {% set clusters = [] %}
          {% for i in range(vc_names | length) %}
          {%   set cluster =  configs[i].clusters[0].cluster %}
          {%   set vc_name = vc_names[i] %}
          {%   set _       = clusters.append({
                 'name':      vc_name,
                 'behavior': 'replace',
                 'cluster':  {
                   'server':                     vcluster_kube_urls[vc_name],
                   'certificate-authority-data': cluster['certificate-authority-data'],
                 },
               })     %}
          {% endfor   %}
          {{ clusters }}
        users: |
          {% set users = [] %}
          {% for i in range(vc_names | length) %}
          {%   set user    =  configs[i].users[0].user %}
          {%   set vc_name = vc_names[i] %}
          {%   set _       = users.append({
                 'name':      vc_name,
                 'behavior': 'replace',
                 'user':     {
                   'client-certificate-data': user['client-certificate-data'],
                   'client-key-data':         user['client-key-data'],
                 },
               })   %}
          {% endfor %}
          {{ users  }}
        contexts: |
          {% set contexts = [] %}
          {% for vc_name in vc_names %}
          {%   set _ = contexts.append({
                 'name':      vc_name,
                 'behavior': 'replace',
                 'context':  {
                   'cluster': vc_name,
                   'user':    vc_name,
                 },
               })     %}
          {% endfor   %}
          {{ contexts }}
        current_context: "{{ context if context in vc_names else omit }}"
      when: vc_names is truthy
      # not worth reporting
      changed_when: false

    - name: Set vcluster_kubeconfig fact
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
      ansible.builtin.set_fact:
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html
        # `preferences` deprecated since v1.34
        # omit_keys: plugins/filter/filters.py
        vcluster_kubeconfig: |
          {{ lookup('ansible.builtin.file', temp_file) | from_yaml |
             omit_keys(['preferences']) if vc_names is truthy else {} }}
  always:
    - name: Delete temp kubeconfig file
      delegate_to: localhost
      vars:
        ansible_python_interpreter: "{{ local_python_interpreter }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
      ansible.builtin.file:
        path: "{{ temp_file }}"
        state: absent
      # not worth reporting
      changed_when: false
