#!/bin/sh

# this script is configured as the Git credential helper in ~/.gitconfig
# that ignores `store` and `erase` subcommands for `git-credential-store`

[ "$1" = get ] || exit 0 # ignore store & erase
for dir in /usr/lib/git-core /usr/libexec/git-core; do
  [ -d $dir ] && exec "$dir/git-credential-store" "$@"
done
