# https://docs.gitea.com/category/administration
# https://docs.gitea.com/administration/config-cheat-sheet
# https://docs.gitea.com/usage/actions/act-runner
---
- name: Install Gitea DevOps platform
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/postgresql.yml
    - vars/opensearch.yml
    - vars/valkey.yml
    - vars/storage.yml
    - vars/minio.yml
    - vars/gitea.configure.yml
    - vars/gitea.yml
  vars: &vars
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ gitea_namespace }}"
    create_ns: false
    chart_ver: "{{ gitea_chart_version if
      gitea_chart_repo_url is match('^http') else none }}"
  pre_tasks:
    # used in init container image tag
    - name: Get Gitea chart appVersion
      vars:
        repo_url: "{{ gitea_chart_repo_url }}"
        chart_ref: gitea
        fact_name: gitea_app_version
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/appversion.yml"
      when: gitea_app_version is undefined

    - name: Get the PostgreSQL image used
      ansible.builtin.include_tasks: "{{ tasks_dir }}/postgresql/image.yml"
      when: postgresql_image is undefined
  tasks:
    - name: Create Gitea ingress secret
      vars:
        secret_name: "{{ gitea_secrets['ingress'] }}"
        create_ns: true
        cert_name: gitea-ingress
        sans:
          - "{{ gitea_fqdns }}"
          - "*.{{ gitea_namespace }}.svc.{{ cluster_domain }}"
          - "*.{{ gitea_namespace }}.svc"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/tls.step.yml"

    - name: Create Gitea database secret
      vars:
        secret_name: "{{ gitea_secrets['database'] }}"
        cert_name: gitea-database
        days: 365
        sans:
          - "{{ gitea_db_user }}"
          - "{{ gitea_db_user }}@{{ homelab_domain }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/tls.step.yml"

    - name: Create Gitea admin secret
      vars:
        admin_user: "{{ gitea_users['admin'] }}"

        # === Inputs ===
        secret_name: "{{ gitea_secrets['admin'] }}"
        secret_data:
          email: "{{    admin_user.email    }}"
          username: "{{ admin_user.username }}"
          password: "{{ admin_user.password }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/generic.yml"

    - name: Create Gitea config secret
      vars:
        secret_name: "{{ gitea_secrets['config'] }}"
        secret_data:
          postgresql-password: "{{ gitea_pg_pass }}"
          opensearch-conn-str: "{{ gitea_os_conn_str }}"
          valkey-conn-str: "{{     gitea_vk_conn_str }}" # for queues, which don't support `?prefix` param
          cache-conn-str: "{{      gitea_vk_conn_str }}?prefix={gitea}:cache:&hset_name={gitea}:cache:keys"
          session-conn-str: "{{    gitea_vk_conn_str }}?prefix={gitea}:session:"
          minio-secret-key: "{{ gitea_minio_key }}"
          smtp-password: "{{ icloud_smtp.passwords['gitea'] }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/generic.yml"

    - name: Create Gitea signing secret
      vars:
        secret_name: "{{ gitea_secrets['signing'] }}"
        secret_data:
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unvault_lookup.html
          privateKey: "{{ lookup('ansible.builtin.unvault', files_dir ~ '/gitea/gnupg/signing.asc') }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/generic.yml"

    - name: Create monitoring scraper secret
      ansible.builtin.include_tasks: "{{ tasks_dir }}/monitoring/scraper.yml"

    - name: Install Gitea Helm chart
      vars:
        repo_name: gitea
        repo_url: "{{ gitea_chart_repo_url }}"
        chart_ref: gitea
        release: "{{ gitea_release_name }}"
        release_ns: "{{ gitea_namespace }}"
        values: "{{ gitea_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{      gitea_secrets['ingress']  }}
          - cert-manager.io/v1 Certificate {{      gitea_secrets['database'] }}
          - cert-manager.io/v1 Certificate {{ monitoring_secrets['scraper']  }}
          - v1 Secret {{ gitea_secrets['admin']   }}
          - v1 Secret {{ gitea_secrets['config']  }}
          - v1 Secret {{ gitea_secrets['signing'] }}
          - v1 Secret {{ gitea_secrets['tokens']  }} ? # optional (created later)
      ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/helmfile.yml"

- name: Configure Gitea installation
  tags: configure
  hosts: localhost
  vars_files: &vars_files
    - vars/gitea.yml
    - vars/gitea.configure.yml
  pre_tasks:
    - name: Wait until Gitea is ready
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
      ansible.builtin.uri:
        url: "{{ gitea_http_url }}/api/healthz"
        return_content: true
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met
      register: site_check
      until:
        - site_check.status      ==  200
        - site_check.json.status == 'pass'
      retries: 20
      delay: 3
  tasks:
    - name: Create/update organization
      vars:
        org: "{{ gitea_organization }}"
        org_name: "{{  org.org_name }}"
        full_name: "{{ org.name     }}"
        email: "{{     org.email    }}"
        desc: "{{      org.desc     }}"
        avatar: "{{    org.avatar   }}"
        location: "{{  org.location }}"
        webhooks: "{{  org.webhooks }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/gitea/org.yml"

    - name: Create/update user account
      vars:
        user: "{{      item.value    }}"
        email: "{{     user.email    }}"
        full_name: "{{ user.name     }}"
        username: "{{  user.username }}"
        password: "{{  user.password }}"
        is_admin: "{{  user.is_admin }}"
        location: "{{  user.location }}"
        avatar: "{{    user.avatar   }}"
        tokens: "{{    user.tokens   }}"
        ssh_keys: "{{  user.ssh_keys }}"
        gpg_keys: "{{  user.gpg_keys }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/gitea/user.yml"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dict2items_filter.html
      loop: "{{ gitea_users | ansible.builtin.dict2items }}"
      loop_control:
        label: "{{ item.key }}"

- name: Build Actions runner image
  tags: build
  hosts: localhost
  vars_files:
    - vars/gitea.yml
  tasks:
    - name: Build image and push to Harbor
      vars:
        image_name: gitea-runner
        image_tag: "{{ actions_runner_image.tag }}"
        build_args:
          RUNNER_IMAGE_TAG: "{{ image_tag }}"
        context_dir: "{{ files_dir }}/gitea/runner"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/oci/build.yml"

- name: Configure Gitea Actions runner
  tags: runner
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/storage.yml
    - vars/harbor.yml
    - vars/gitea.yml
  vars:
    <<: *vars
    chart_ver: "{{ actions_chart_version if
      actions_chart_repo_url is match('^http') else none }}"
  pre_tasks:
    # used in metrics service labels
    - name: Get Actions chart appVersion
      vars:
        repo_url: "{{ actions_chart_repo_url }}"
        chart_ref: actions
        fact_name: actions_app_version
      ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/appversion.yml"

    - name: Look up existing runner token
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_info_module.html
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: Secret
        name: "{{ gitea_secrets['runner'] }}"
        namespace: "{{ gitea_namespace }}"
      register: token_info
  tasks:
    - name: Get runner registration token
      when: token_info.resources is falsy
      block:
        - name: Get tokens from Gitea secret
          ansible.builtin.include_tasks: "{{ tasks_dir }}/gitea/tokens.yml"
          # sets fact: gitea_tokens

        - name: Get runner registration token
          ansible.builtin.uri:
            method: POST
            url: "{{ gitea_api_url }}/admin/actions/runners/registration-token"
            # https://docs.gitea.com/development/api-usage#authentication
            headers:
              Authorization: token {{ gitea_tokens['admin'] }}
            return_content: true
          register: runner_token

        - name: Store runner token in secret
          vars:
            secret_name: "{{ gitea_secrets['runner'] }}"
            secret_data:
              token: "{{ runner_token.json.token }}"
          ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/generic.yml"

    # env vars set in all job containers
    - name: Create runner dotenv secret
      vars:
        ci_reg_path: "{{ harbor_container_registry }}/{{ harbor_default_project }}"

        # === Inputs ===
        secret_name: "{{ gitea_secrets['dotenv'] }}"
        secret_data:
          job.env: |
            CI_REGISTRY={{ harbor_url }}
            CI_REGISTRY_PATH={{ ci_reg_path }}
            CI_REGISTRY_USER={{ gitea_harbor_user }}
            CI_REGISTRY_PASSWORD={{ gitea_harbor_pass }}
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/generic.yml"

    - name: Install Actions Helm chart
      vars:
        # deploy extra objects like runner ServiceAccount
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_lookup.html
        extra_objs: "{{ lookup('ansible.builtin.template',
          templates_dir ~ '/gitea/runner/extras.yaml.j2') }}"

        # === Inputs ===
        repo_name: gitea
        repo_url: "{{ actions_chart_repo_url }}"
        chart_ref: actions
        release: "{{ actions_release_name }}"
        release_ns: "{{ gitea_namespace }}"
        values: "{{ actions_chart_values }}"

        patches:
          merge_patches:
            - apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: "{{ actions_app_name }}"
                namespace: "{{ gitea_namespace }}" # required
              spec:
                revisionHistoryLimit: 2
                persistentVolumeClaimRetentionPolicy:
                  whenScaled: Retain
                  whenDeleted: Delete

                template:
                  spec:
                    initContainers:
                      - name: dind
                        # be conservative with declaring failure
                        # because Buildah build in host mode can
                        # grind the node to a halt
                        startupProbe: &probe
                          periodSeconds: 20
                          timeoutSeconds: 5
                          successThreshold: 1
                          failureThreshold: 6
                        livenessProbe: *probe

                    containers:
                      - name: runner
                        # allow building OCI images using Buildah
                        securityContext:
                          runAsUser: 0
                          runAsGroup: 0
                          appArmorProfile:
                            type: Localhost
                            localhostProfile: buildah
                        # expose port for app Service
                        ports:
                          - name: metrics
                            containerPort: "{{ actions_metrics_port }}"
                            protocol: TCP

        extras: # adopt extra resources into Helm release
          - v1 Secret {{ gitea_secrets['runner'] }}
          - v1 Secret {{ gitea_secrets['dotenv'] }}
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/from_yaml_all_filter.html
          - "{{ extra_objs | from_yaml_all }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/helmfile.yml"

- name: Migrate projects from GitHub
  tags: projects
  hosts: localhost
  vars_files: *vars_files
  pre_tasks:
    - name: Get tokens from Gitea secret
      ansible.builtin.include_tasks: "{{ tasks_dir }}/gitea/tokens.yml"
      when: gitea_tokens is undefined
  tasks:
    - name: Migrate project from GitHub
      vars:
        projects: "{{ gitea_projects | selectattr('from', '==', 'github') }}"

        # === Inputs ===
        gitea_token: "{{ gitea_tokens['erhhung-repos'] }}"
        source_repo: "{{      item.source_repo     }}"
        target_repo: "{{      item.target_repo     }}"
        avatar: "{{           item.avatar          }}"
        default_branch: "{{   item.default_branch  }}"
        run_workflow: "{{     item.run_workflow    }}"
        workflow_inputs: "{{  item.workflow_inputs }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/gitea/migrate.github.yml"
      loop: "{{ projects }}"
      loop_control:
        label: "{{ item.target_repo | basename }}"

- name: Configure Gitea dashboards
  tags: dashboards
  hosts: localhost
  vars_files:
    - vars/gitea.yml
  tasks:
    - name: Import Grafana dashboards
      vars:
        dashboards: "{{ gitea_grafana_dashboards }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/grafana/dashboards.yml"
