# https://goharbor.io/
# https://goharbor.io/docs/latest/install-config/harbor-ha-helm
---
- name: Install Harbor on K3s cluster
  tags: install
  hosts: "{{ k3s_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/storage.yml
    - vars/harbor.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ k3s_kubeconfig }}"
  tasks:
    - name: Create Harbor ingress secret
      vars:
        secret_name: "{{ harbor_secrets['ingress'] }}"
        secret_ns: "{{ harbor_namespace }}"
        cert_name: harbor-ingress
        sans: "{{ [harbor_fqdn] }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/tls.step.yml"

    - name: Install Harbor Helm chart
      vars:
        repo_name: harbor
        repo_url: https://helm.goharbor.io
        chart_ref: harbor
        chart_ver: "{{ harbor_chart_version }}"
        release: "{{ harbor_release_name }}"
        release_ns: "{{ harbor_namespace }}"
        values: "{{ harbor_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ harbor_secrets['ingress'] }}
      ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/helmfile.yml"

# https://github.com/goharbor/harbor-cli#installation
- name: Install Harbor CLI tool
  tags: cli
  hosts: k8s_hosts
  vars_files:
    - vars/harbor.yml
  tasks:
    - name: Install Harbor CLI tool
      become: true
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |
        set -o pipefail

        REL="https://github.com/goharbor/harbor-cli/releases"
        VER=$(curl -ILs "$REL/latest" | sed -En 's/^location:.+\/tag\/v(.+)\r$/\1/p')

        # check if latest version already installed
        command -v harbor &> /dev/null && {
          ver=$(v=`harbor version | yq .Version`; echo ${v#v})
          [ "$ver" == "$VER" ] && exit 9 # no change
        }
        ARCH=$(uname -m | sed -e 's/aarch64/arm64/' -e 's/x86_64/amd64/')
        tarball="$REL/download/v${VER}/harbor-cli_${VER}_linux_${ARCH}.tar.gz"

        # this project is known to create a new release but fail to
        # attach asset files for download, so first ensure that the
        # tarball actually exists
        status=$(curl -sLI -o /dev/null -w '%{http_code}' "$tarball")
        [[ "$status" -eq 404 && "$ver" ]] && exit 9 # skip upgrade

        curl -fsSL "$tarball" | tar -xz --no-same-owner --wildcards "*harbor-cli"
        mv -f harbor-cli harbor
      args:
        executable: /bin/bash
        chdir: /usr/local/bin
      register: install_cli
      changed_when: install_cli.rc == 0
      failed_when: install_cli.rc not in [0,9]

    # https://github.com/goharbor/harbor-cli/tree/main/doc/cli-config/_index.md
    # https://github.com/goharbor/harbor-cli/tree/main/doc/cli-encryption/_index.md
    - name: Configure Harbor CLI login
      ansible.builtin.shell: |
        # restart Bash and load .bash_aliases
        exec /bin/bash -l <<'EOT'
        . .bash_aliases
        set -o pipefail

        exists="$(harbor context list -o yaml | \
          yq -r '.credentials[] | select(.username == "admin")')"
        [ "$exists" ] && exit 9 # no change

        [ "$HARBOR_ENCRYPTION_KEY" ] || {
          export HARBOR_ENCRYPTION_KEY=$(openssl rand -base64 32)
          rm -rf "$HOME/.harbor"

          # BASH_ENV_DIR is set in .bash_aliases
          cat <<EOF > "$BASH_ENV_DIR/harbor.env"
        HARBOR_ENCRYPTION_KEY="$HARBOR_ENCRYPTION_KEY"
        EOF
        }
        harbor login {{ harbor_url }} --context-name admin \
            -u {{ harbor_admin_user }} -p '{{ harbor_admin_pass }}'
        EOT
      register: config_cli
      changed_when: config_cli.rc == 0
      failed_when: config_cli.rc not in [0,9]

- name: Configure Harbor registry
  tags: configure
  hosts: "{{ k3s_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/harbor.yml
    - vars/harbor.configure.yml

    # these are only needed for their
    # *_harbor_user|_harbor_pass vars
    - vars/gitea.yml
    - vars/gitlab.yml
    - vars/jenkins.yml
    - vars/buildkite.yml
  vars:
    # https://harbor.fourteeners.local/devcenter-api-2.0
    api_base: "{{ harbor_url }}/api/v2.0"
    api_auth: "{{ harbor_admin_user }}:{{ harbor_admin_pass }}"
    uri_auth: &uri-auth
      url_username: "{{ harbor_admin_user }}"
      url_password: "{{ harbor_admin_pass }}"
      force_basic_auth: true
  pre_tasks:
    - name: Get Harbor system settings
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
      ansible.builtin.uri:
        url: "{{ api_base }}/configurations"
        <<: *uri-auth
        return_content: true
      register: system_settings
      retries: 3
      delay: 3

    - name: Get library project config
      ansible.builtin.uri:
        url: "{{ api_base }}/projects/{{ harbor_default_project }}"
        # no auth required
        return_content: true
      register: project_config
      retries: 3
      delay: 3
  tasks:
    - name: Configure system settings
      vars:
        existing: "{{ system_settings.json }}"
        settings: |
          {% set settings = {} %}
          {% for key, value in harbor_settings.items() %}
          {%   if key in existing and existing[key].editable == true
                                  and existing[key].value    != value %}
          {%     set _ = settings.update({key: value}) %}
          {%   endif  %}
          {% endfor   %}
          {{ settings }}
      ansible.builtin.uri:
        method: PUT
        url: "{{ api_base }}/configurations"
        <<: *uri-auth
        body_format: json
        body: "{{ settings }}"
      when: settings is truthy
      changed_when: true

    - name: Configure library project
      vars:
        metadata: "{{ project_config.json.metadata }}"
        auto_sbom: "{{ metadata.auto_sbom_generation | default('false') | bool }}"
        auto_scan: "{{ metadata.auto_scan            | default('false') | bool }}"
      ansible.builtin.uri:
        method: PUT
        url: "{{ api_base }}/projects/{{ harbor_default_project }}"
        <<: *uri-auth
        body_format: json
        body:
          metadata:
            # all values must be strings
            auto_sbom_generation: "true"
            auto_scan: "true"
      when: >-
        not auto_sbom or
        not auto_scan
      changed_when: true

    # could also be done using the CLI
    - name: Add non-admin Harbor users
      ansible.builtin.shell: |
        set -o pipefail

        get_user_id() {
          local api_url="{{ api_base }}/users/search?username=$1"
          curl -sku {{ api_auth }} "$api_url" | jq -r .[].user_id
        }
        user_id="$(get_user_id {{ item.username }})"
        [ "$user_id" ] && exit 9 # no change

        params=(
          realname="{{ item.real_name }}"
             email="{{ item.email     }}"
          username="{{ item.username  }}"
          password="{{ item.password | quote }}"
           comment="{{ item.comment  | quote if item.comment is defined else '' }}"
        )
        curl -X POST -sku {{ api_auth }} \
             -H 'Content-Type: application/json' \
             -d "$(jo "${params[@]}")" \
             {{ api_base }}/users

        user_id="$(get_user_id {{ item.username }})"
        [ "$user_id" ] || exit 1

        # add user to default library project
        role_id={{ harbor_roles[item.role] }}
        params=(
          member_user=$(jo user_id=$user_id)
          role_id=$role_id
        )
        curl -X POST -sku {{ api_auth }} \
             -H 'Content-Type: application/json' \
             -d "$(jo "${params[@]}")" \
             {{ api_base }}/projects/{{ harbor_default_project }}/members
      args:
        executable: /bin/bash
      loop: "{{ harbor_users }}"
      loop_control:
        label: "{{ item.username }}"
      register: create_users
      changed_when: create_users.rc == 0
      failed_when: >-
        create_users.rc not in [0,9] or
        create_users.stdout is search('errors')

- name: Mirror images into Harbor
  tags:
    - mirror
    - copy
  hosts: "{{ k3s_control_plane_host }}"
  vars_files: &vars_files
    - vars/kubernetes.yml
    - vars/harbor.yml
    - vars/harbor.configure.yml
  vars:
    mirror_images: |
      {% set images = [] %}
      {% for image    in harbor_mirror_images %}
      {%   set parts = image.src.split('/')   %}
      {%   set dest  = image.dest | default('library/'~ parts[-1]) %}
      {%   set _     = images.append({
             'reg':  parts[0],
             'src':  image.src,
             'dest':      dest,
             'proj':      dest.split('/')[0],
             'repo': parts[-1].split(':')[0],
             'tag':  parts[-1].split(':')[1] if ':' in parts[-1] else 'latest',
           })   %}
      {% endfor %}
      {{ images }}
    preamble: &preamble |-
      # restart Bash and load .bash_aliases
      exec /bin/bash -l <<'EOT'
      # don`t load .rancher_api
      ADMIN_PASS=none
      . .bash_aliases
      set -eo pipefail
  pre_tasks:
    - name: Determine copying needs
      # noqa risky-shell-pipe
      ansible.builtin.shell: |
        {{ preamble }}

        proj_list=($(harbor project list -o json | jq -r '.[].name'))
        sources=() registries=() projects=()

        add_unique() {
          local -n array="$1"; local value="$2"
          [[ " ${array[*]} " == *" $value "* ]] || \
            array+=($value)
        }
        {% for image in mirror_images %}
        repo={{ image.proj }}/{{ image.repo }}

        id=$(harbor artifact list $repo -o json 2> /dev/null | \
          jq --arg tag {{ image.tag }} -r '.Payload[] |
            select($tag == (.tags // [])[].name) | .id'
        ) && [ "$id" ] || sources+=({{ image.src }})

        if [ ! "$id" ]; then
          # add registries to log into
          add_unique registries {{ image.reg }}

          # add projects to be created
          [[ " ${proj_list[*]} " == *" {{ image.proj }} "* ]] || \
            add_unique projects {{ image.proj }}
        fi
        {% endfor %}

        jo -p sources="$(jo -a -- <<< ""    "${sources[@]}")" \
             projects="$(jo -a -- <<< ""   "${projects[@]}")" \
           registries="$(jo -a -- <<< "" "${registries[@]}")"
        EOT
      register: copy_needs
      changed_when: false

    - name: Set image copying facts
      vars:
        needs: "{{ copy_needs.stdout | from_json }}"
      ansible.builtin.set_fact:
        login_registries: "{{ needs['registries'] }}"
        create_projects: "{{  needs['projects']   }}"
        image_sources: "{{    needs['sources']    }}"
  tasks:
    - name: Log in to registries
      ansible.builtin.shell: |
        registries=(
          {{ login_registries | join(' ') }}
          {{ harbor_container_registry    }}
        )
        for registry in "${registries[@]}"; do
          user={{ user_erhhung.username }}
          unset pass

          case "$registry" in
              # only Harbor admins can create projects
              harbor*) user='{{ harbor_admin_user   }}'
                       pass='{{ harbor_admin_pass   }}' ;;
            docker.io) pass='{{ docker_access_token }}' ;;
              ghcr.io) pass='{{ github_access_token }}' ;;
          esac

          [ "$pass" ] || {
            echo "No credentials provided for $registry."
            echo "Access will be public only."
            continue
          }
          echo "Logging in to $registry..."
          skopeo login $registry -u $user -p "$pass"
          rc=0
        done
        set +e; exit ${rc-9}
      args:
        executable: /bin/bash
      register: reg_logins
      when: login_registries is truthy
      changed_when: reg_logins.rc == 0
      failed_when: reg_logins.rc not in [0,9]

    - name: Create Harbor project
      ansible.builtin.shell: |
        {{ preamble }}

        # https://unioslo.github.io/harbor-cli/commands/project#project-create
        harbor project create {{ item }} --public --storage-limit=-1
        EOT
      loop: "{{ create_projects }}"
      changed_when: true

    # https://github.com/containers/skopeo#copying-images
    - name: Copy image into Harbor
      vars:
        image: "{{ mirror_images | selectattr('src', '==', item) | first }}"
        # use specified destination tag if provided; use source tag otherwise
        dest_path: "{{ image.dest ~ ('' if ':' in image.dest else ':'~ image.tag) }}"
        image_dest: "{{ harbor_container_registry }}/{{ dest_path }}"
      ansible.builtin.shell: |
        set -eo pipefail

        # https://github.com/containers/skopeo/tree/main/docs/skopeo-copy.1.md
        ARCH=$(uname -m | sed -e 's/aarch64/arm64/' -e 's/x86_64/amd64/')
        skopeo --override-os linux --override-arch $ARCH \
          copy --multi-arch system --retry-times 2 \
          docker://{{ image.src  }} \
          docker://{{ image_dest }}
      args:
        executable: /bin/bash
      loop: "{{ image_sources }}"
      loop_control:
        label: "{{ dest_path }}"
      changed_when: true
      timeout: 900

- name: Mirror charts into Harbor
  tags:
    - mirror
    - copy
  hosts: "{{ k3s_control_plane_host }}"
  vars_files: *vars_files
  vars:
    mirror_charts: |
      {% set charts = [] %}
      {% for chart    in harbor_mirror_charts %}
      {%   set repo = chart.src |  dirname %}
      {%   set base = chart.src | basename %}
      {%   set _    = charts.append({
             'src':  chart.src,
             'dest': chart.dest,
             'repo': repo,
             'name': base.split('@')[0],
             'ver':  base.split('@')[1] if '@' in base else 'latest',
           })   %}
      {% endfor %}
      {{ charts }}
    preamble: *preamble
    tmp_path: /tmp/charts
  pre_tasks:
    - name: Determine copying needs
      # noqa risky-shell-pipe
      ansible.builtin.shell: |
        {{ preamble }}

        if ! harbor project search charts &> /dev/null; then
          # store charts under "charts" project; don`t clobber stdout
          harbor project create charts --public --storage-limit=-1 >&2
        fi
        sources=()

        {% for chart in mirror_charts %}
        repo={{ chart.dest }}

        id=$(harbor artifact list $repo -o json 2> /dev/null | \
          jq --arg ver {{ chart.ver }} -r '.Payload[] |
            select($ver == (.tags // [])[].name) | .id'
        ) && [ "$id" ] || sources+=({{ chart.src }})
        {% endfor %}

        if {% raw %}(( ${#sources[@]} )){% endraw %}; then
          # this #} is just to satisfy ansible-lint parser
          mkdir -p {{ tmp_path }}
        fi
        jo -p sources="$(jo -a -- <<< "" "${sources[@]}")"
        EOT
      register: copy_needs
      changed_when: false

    - name: Set chart copying facts
      vars:
        needs: "{{ copy_needs.stdout | from_json }}"
      ansible.builtin.set_fact:
        chart_sources: "{{ needs['sources'] }}"
  tasks:
    - name: Do Helm login to Harbor
      ansible.builtin.shell: |
        set -eo pipefail

        echo -n '{{ harbor_admin_pass  }}' | helm registry login  \
          {{ harbor_container_registry }} -u {{ harbor_admin_user }} \
          --password-stdin
      args:
        executable: /bin/bash
      when: chart_sources is truthy
      changed_when: true

    # https://goharbor.io/docs/main/working-with-projects/working-with-oci/working-with-helm-oci-charts#pushing-oci-helm-charts
    - name: Copy chart into Harbor
      vars:
        chart: "{{ mirror_charts | selectattr('src', '==', item) | first }}"
        chart_dest: oci://{{ harbor_container_registry }}/{{
          chart.dest | dirname }}
      ansible.builtin.shell: |
        helm pull --repo {{ chart.repo }} {{ chart.name }} --version {{ chart.ver }}

        tarball={{ chart.name }}-{{ chart.ver }}.tgz
        [ -f "$tarball" ] || {
          echo >&2 "Failed to pull Helm chart \"{{ chart.name }}@{{
            chart.ver }}\" from {{ chart.repo }}"
          exit 1
        }
        trap "rm -f \$tarball" EXIT

        helm push $tarball {{ chart_dest }}
      args:
        executable: /bin/bash
        chdir: "{{ tmp_path }}"
      loop: "{{ chart_sources }}"
      loop_control:
        label: "{{ chart.dest ~'@'~ chart.ver }}"
      changed_when: true
