# https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
---
- name: Install PostgreSQL on RKE cluster
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/metallb.yml
    - vars/storage.yml
    - vars/monitoring.yml
    - vars/postgresql.yml

    # these are only needed for
    # their *_db_user variables
    - vars/keycloak.yml
    - vars/policyreporter.yml
    - vars/gitea.yml
    - vars/gitlab.yml
    - vars/awx.yml
    - vars/litellm.yml
    - vars/openwebui.yml
    - vars/flowise.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ postgresql_namespace }}"
    create_ns: false
  pre_tasks:
    - name: Is the monitoring stack ready?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: "{{ tasks_dir }}/monitoring/stackready.yml"
      when: monitoring_stack_ready is undefined
  tasks:
    - name: Create PostgreSQL node secret
      vars:
        secret_name: "{{ postgresql_secrets['node-tls'] }}"
        create_ns: true
        cert_name: postgresql-node
        sans:
          - postgresql-node
          - "{{ postgresql_fqdns }}"
          - "*.{{ postgresql_namespace }}.svc.{{ cluster_domain }}"
          - "*.{{ postgresql_namespace }}.svc"
          - "{{ metallb_vips['postgresql'] }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/tls.step.yml"

    - name: Create Pgpool exporter secret
      ansible.builtin.include_tasks: "{{ tasks_dir }}/monitoring/scraper.yml"

    - name: Install PostgreSQL HA Helm chart
      vars:
        repo_name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
        chart_ref: postgresql-ha
        chart_ver: "{{ postgresql_chart_version }}"
        release: "{{ postgresql_release_name }}"
        release_ns: "{{ postgresql_namespace }}"
        values: "{{ postgresql_chart_values }}"

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ postgresql_secrets['node-tls'] }}
          - cert-manager.io/v1 Certificate {{ monitoring_secrets['scraper']  }}

        wait_timeout: 600
        task_timeout: 1800
      ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/helmfile.yml"

    # this task creates roles defined after initial deployment when
    # the one-time init script ("templates/postgresql/init.sql.j2")
    # executed the same `CREATE ROLE` commands
    - name: Create missing PostgreSQL roles
      vars:
        replicas: "{{ postgresql_chart_values.postgresql.replicaCount }}"
        # prepend: plugins/filter/filters.py
        sts_pods: "{{ range(replicas) | map('string') | map('prepend',
          postgresql_release_name ~'-postgresql-') }}"
        script: |-
          run_query() {
            psql -U postgres -tAc "$1"
          }
          is_primary() {
            local result=$(run_query 'SELECT pg_is_in_recovery()')
            if [ "$result" == t ]; then
              echo >&2 "Replica node"
              return 1
            fi
            echo >&2 "Primary node"
          }
          role_exists() {
            local result=$(run_query "SELECT EXISTS (SELECT FROM pg_roles WHERE rolname = '$1')")
            [ "$result" == t ]
          }
          rc=9; is_primary || exit $rc
          while read -r  role pass; do
            role_exists $role && continue

            echo >&2 "Creating role: $role"
            run_query >&2 "CREATE ROLE $role WITH CREATEDB LOGIN PASSWORD '$pass'"
            rc=0
          done <<'EOF'
          {% for role in postgresql_users[2:] %}
          {{ role }} {{ vars[role ~'_pg_pass'] | default(pgpool_pass) }}
          {% endfor %}
          EOF

          exit $rc
      # https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_exec_module.html
      kubernetes.core.k8s_exec:
        kubeconfig: "{{ kubeconfig }}"
        namespace: "{{ postgresql_namespace }}"
        pod: "{{ item }}"
        container: postgresql
        command: bash -c {{ script | quote }}
      loop: "{{ sts_pods }}"
      register: create_roles
      changed_when: create_roles.rc == 0
      failed_when: create_roles.rc not in [0,9]

- name: Configure PostgreSQL dashboards
  tags: dashboards
  hosts: localhost
  vars_files:
    - vars/postgresql.yml
  tasks:
    - name: Import Grafana dashboards
      vars:
        dashboards: "{{ postgresql_grafana_dashboards }}"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/grafana/dashboards.yml"
      when: grafana_api_server_online | default(true)
