# https://grafana.com/docs/tempo
# https://grafana.com/docs/grafana/latest/visualizations/explore/trace-integration
---
- name: Install Tempo tracing backend
  tags: install
  hosts: "{{ rke_control_plane_host }}"
  vars_files:
    - vars/kubernetes.yml
    - vars/monitoring.yml
    - vars/observability.yml
    - vars/storage.yml
    - vars/minio.yml
    - vars/tempo.yml
  vars:
    # required kubernetes>=24.2 package only in user virtualenv
    ansible_python_interpreter: "{{ venv_python_interpreter }}"
    kubeconfig: "{{ rke_kubeconfig }}"
    secret_ns: "{{ tempo_namespace }}"
    create_ns: false
  tasks:
    - name: Create S3 credentials secret
      vars:
        secret_name: "{{ tempo_secrets['s3-creds'] }}"
        secret_data:
          MINIO_SECRET_KEY: "{{ minio_client_pass }}"
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_tasks_module.html
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/generic.yml"

    # tempo-query no longer exposes Jaeger UI, but
    # cert is still used for Tempo's HTTP endpoint
    - name: Create Jaeger ingress secret
      vars:
        secret_name: "{{ tempo_secrets['ingress'] }}"
        cert_name: jaeger-ingress
        sans:
          - "{{ jaeger_fqdns }}"
          - "{{ tempo_release_name }}.{{ tempo_namespace }}.svc.{{ cluster_domain }}"
          - "{{ tempo_release_name }}.{{ tempo_namespace }}.svc"
      ansible.builtin.include_tasks: "{{ tasks_dir }}/k8s/secrets/tls.step.yml"

    - name: Create monitoring scraper secret
      ansible.builtin.include_tasks: "{{ tasks_dir }}/monitoring/scraper.yml"

    - name: Install Tempo Helm chart
      vars:
        repo_name: grafana
        repo_url: https://grafana-community.github.io/helm-charts
        chart_ref: tempo
        chart_ver: "{{ tempo_chart_version }}"
        release: "{{ tempo_release_name }}"
        release_ns: "{{ tempo_namespace }}"
        values: "{{ tempo_chart_values }}"

        patches:
          merge_patches:
            - |
              {% if values.tempoQuery.enabled %}
              apiVersion: apps/v1
              kind: StatefulSet
              metadata:
                name: {{ tempo_release_name }}
                namespace: {{ tempo_namespace }}
              spec:
                template:
                  spec:
                    containers:
                      # tempo-query:2.6.0
                      - name: tempo-query
                        args:
                          - --query.base-path=/
                          - --grpc-storage-plugin.configuration-file=/conf/tempo-query.yaml
              {% endif %}
          json_patches:
            # Helm chart doesn't currently allow
            # providing serviceMonitor.tlsConfig
            - |
              target:
                group: monitoring.coreos.com
                version: v1
                kind: ServiceMonitor
                name: {{ tempo_release_name }}
                namespace: {{ tempo_namespace }}
              patch:
                - op: add
                  # endpoints[0]: tempo-prom-metrics
                  path: /spec/endpoints/0/path
                  value: /metrics
                - op: add
                  path: /spec/endpoints/0/scheme
                  value: https
                - op: add
                  path: /spec/endpoints/0/tlsConfig
                  value: {{ metric_scraper_tls_config }}
              {% if values.tempoQuery.enabled %}
                - op: add
                  # endpoints[1]: jaeger-metrics
                  path: /spec/endpoints/1/path
                  value: /metrics
                - op: add
                  path: /spec/endpoints/1/scheme
                  value: http
              {% endif %}

        extras: # adopt extra resources into Helm release
          - cert-manager.io/v1 Certificate {{ tempo_secrets['ingress'] }}
          - v1 Secret {{ tempo_secrets['s3-creds'] }}
      ansible.builtin.include_tasks: "{{ tasks_dir }}/helm/helmfile.yml"
